#ifndef FREEDOM_DRAGONICA_SCRIPTING_WORLDOBEJCT_EFFECT_LWROPE_H
#define FREEDOM_DRAGONICA_SCRIPTING_WORLDOBEJCT_EFFECT_LWROPE_H

#include "PgScripting.h"
#include "PgRope.H"

class	lwPoint3;

LW_CLASS(PgRope, Rope)

	lwPoint3	GetStartPos();
	lwPoint3	GetEndPos();

LW_CLASS_END;
#endif // FREEDOM_DRAGONICA_SCRIPTING_WORLDOBEJCT_EFFECT_LWROPE_H