#ifndef FREEDOM_DRAGONICA_SCRIPTING_WORLDOBEJCT_ACTOR_LWUNIT_PTR_ARRAY_H
#define FREEDOM_DRAGONICA_SCRIPTING_WORLDOBEJCT_ACTOR_LWUNIT_PTR_ARRAY_H

#include "PgScripting.h"
#include "Variant/PgTotalObjectMgr.h"
#include "lwUnit.h"

LW_CLASS(UNIT_PTR_ARRAY, UNIT_PTR_ARRAY)
	lwUnit GetUnit(int iIndex);
	void AddUnit(lwUnit kUnit);
LW_CLASS_END;
#endif // FREEDOM_DRAGONICA_SCRIPTING_WORLDOBEJCT_ACTOR_LWUNIT_PTR_ARRAY_H