#ifndef FREEDOM_DRAGONICA_CONTENTS_MISSIONMUTATOR_PGMISSIONMUTATOR_H
#define FREEDOM_DRAGONICA_CONTENTS_MISSIONMUTATOR_PGMISSIONMUTATOR_H

class PgMissionMutator
{
public:
	PgMissionMutator(void);
	~PgMissionMutator(void);
};

#endif // FREEDOM_DRAGONICA_CONTENTS_MISSIONMUTATOR_PGMISSIONMUTATOR_H