#ifndef FREEDOM_DRAGONICA_CONTENTS_MINIMAP_PGMINIMAP_TYPE_H
#define FREEDOM_DRAGONICA_CONTENTS_MINIMAP_PGMINIMAP_TYPE_H


typedef struct tagMinimapIconInfo
{
	int Type;
	std::wstring kIconID;
	std::wstring kIconName;
}SMINIMAP_ICON_INFO;

typedef std::list< SMINIMAP_ICON_INFO > CONT_MINIMAP_ICON_INFO;


#endif // FREEDOM_DRAGONICA_CONTENTS_MINIMAP_PGMINIMAP_TYPE_H