# Macros format

macro(COSMOS_STATIC_LIB_CONFIG_OUTPUT)

    set_target_properties(${PROJECT_NAME}
        PROPERTIES
        DEBUG_POSTFIX _MDd
        RELEASE_POSTFIX _MDo
        RELWITHDEBINFO_POSTFIX _MD
        FOLDER ${PROJECT_FOLDER}
        RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${cosmos_SOURCE_DIR}/Lib/"
        LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO "${cosmos_SOURCE_DIR}/Lib/"
        ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO "${cosmos_SOURCE_DIR}/Lib/"
        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${cosmos_SOURCE_DIR}/Lib/"
        LIBRARY_OUTPUT_DIRECTORY_RELEASE "${cosmos_SOURCE_DIR}/Lib/"
        ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${cosmos_SOURCE_DIR}/Lib/"
        RUNTIME_OUTPUT_DIRECTORY_DEBUG "${cosmos_SOURCE_DIR}/Lib/"
        LIBRARY_OUTPUT_DIRECTORY_DEBUG "${cosmos_SOURCE_DIR}/Lib/"
        ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${cosmos_SOURCE_DIR}/Lib/"
    )

endmacro(COSMOS_STATIC_LIB_CONFIG_OUTPUT)

macro(WEAPONS_STATIC_LIB_CONFIG_OUTPUT)

    set_target_properties(${PROJECT_NAME}
        PROPERTIES
        FOLDER ${PROJECT_FOLDER}
        DEBUG_POSTFIX _MDd
        RELEASE_POSTFIX _MDo
        RELWITHDEBINFO_POSTFIX _MD
        RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_CURRENT_SOURCE_DIR}/../Lib/"
        LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_CURRENT_SOURCE_DIR}/../Lib/"
        ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_CURRENT_SOURCE_DIR}/../Lib/"
        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_SOURCE_DIR}/../Lib/"
        LIBRARY_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_SOURCE_DIR}/../Lib/"
        ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_SOURCE_DIR}/../Lib/"
        RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_SOURCE_DIR}/../Lib/"
        LIBRARY_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_SOURCE_DIR}/../Lib/"
        ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_SOURCE_DIR}/../Lib/"
    )

endmacro(WEAPONS_STATIC_LIB_CONFIG_OUTPUT)

