#ifndef CONSENT_CONSENTSERVER_MAINFRAME_CONSTANT_H
#define CONSENT_CONSENTSERVER_MAINFRAME_CONSTANT_H

#pragma pack(1)


typedef enum
{
	EVAR_KIND_NONE = 0,
	EVAR_KIND_GALA_CASH = 1,
} EVAR_KIND_CONSTANT;

typedef enum
{
	EVAR_CN_GALACASH_NONE = 0,
	EVAR_CN_GALACASH_GIFT2BUYITEM = 1,
} EVAR_CN_GALACASH;

#pragma pack()

#endif // CONSENT_CONSENTSERVER_MAINFRAME_CONSTANT_H