#ifndef CONSENT_CONSENTSERVER_NETWORK_PGRECVFROMMMC_H
#define CONSENT_CONSENTSERVER_NETWORK_PGRECVFROMMMC_H

extern bool OnRecvFromMCtrl( WORD wkType, BM::Stream * const pkPacket, CEL::CSession_Base *pkSession);

#endif // CONSENT_CONSENTSERVER_NETWORK_PGRECVFROMMMC_H