#ifndef WEAPON_AILEPACK_FPT_FPT_CONSTANT_H
#define WEAPON_AILEPACK_FPT_FPT_CONSTANT_H

namespace FPT {

typedef enum
{
	EAUTH_ERROR_SUCCESS = 0,
	EAUTH_ERROR_UNKNOWN = 1,
} EAUTH_ERROR;


};

#endif // WEAPON_AILEPACK_FPT_FPT_CONSTANT_H