DoFile("Skill/SkillHelpFunc/SkillHelpFunc.lua")
DoFile("Skill/melee.lua")
DoFile("Skill/FloatMelee.lua")
DoFile("Skill/melee_default.lua")
DoFile("Skill/Melee_Blow_Up.lua")
DoFile("Skill/Melee_Knock_Back.lua")
DoFile("Skill/Melee_Drop.lua")
DoFile("Skill/archer_shot.lua")
DoFile("Skill/DownShot.lua")
DoFile("Skill/ArcherDownShot.lua")
DoFile("Skill/ArcherJumpShot.lua")
DoFile("Skill/JumpShot.lua")
DoFile("Skill/Mon_Melee.lua")
DoFile("Skill/Mon_Melee_Castani.lua")
DoFile("Skill/Mon_RangeAttack.lua")
DoFile("Skill/Mon_WhirlWind.lua")
DoFile("Skill/Mon_JumpDownCrash.lua")
DoFile("Skill/Mon_JumpDownCrash02.lua")
DoFile("Skill/Mon_JumpDownCrash_Diag.lua")
DoFile("Skill/DashAttack.lua")
DoFile("Skill/Melee_Charge_Attack.lua")
DoFile("Skill/Magician_Charge_Attack.lua")
DoFile("Skill/Archer_Charge_Attack.lua")
DoFile("Skill/Fighter_Jump_Attack.lua")
DoFile("Skill/Down_Attack.lua")
DoFile("Skill/projectile_default.lua")
DoFile("Skill/projectile_handGrenade.lua")
DoFile("Skill/Venom.lua")
DoFile("Skill/BrotherIsReturn.lua")
DoFile("Skill/BrotherIsReturn_Play.lua")
DoFile("Skill/BrotherIsGone.lua")
DoFile("Skill/BrotherIsGone_Play.lua")
DoFile("Skill/Gimilet.lua")
DoFile("Skill/Claymore_Play.lua")
DoFile("Skill/HammerCrush.lua")
DoFile("Skill/ShoulderTackle.lua")
DoFile("Skill/StormBlade.lua")
DoFile("Skill/SwordDance.lua")
DoFile("Skill/MagMultiShot.lua")
DoFile("Skill/Fortress.lua")
DoFile("Skill/Archer_Power_Shot.lua")
DoFile("Skill/ArcherFloatShot.lua")
DoFile("Skill/Archer_Charge_Arrow.lua")
DoFile("Skill/Pressure.lua")
DoFile("Skill/Pressure_Play.lua")
DoFile("Skill/BackStepShot.lua")
DoFile("Skill/MoonDance.lua")
DoFile("Skill/ChainLightning.lua")
DoFile("Skill/ShadowLeap.lua")
DoFile("Skill/wheelwind.lua")
DoFile("Skill/HeadSpin.lua")
DoFile("Skill/MegaDrill.lua")
DoFile("Skill/AutoShootSystem_Fire.lua")
DoFile("Skill/AutoShootSystem_Play.lua")
DoFile("Skill/WindMill.lua")
DoFile("Skill/Meteor.lua")
DoFile("Skill/OctopusInk.lua")
DoFile("Skill/GroundMine.lua")
DoFile("Skill/MagnumBreak.lua")
DoFile("Skill/Mana_Shield.lua")
DoFile("Skill/Detonator.lua")
DoFile("Skill/Haphazard.lua")
DoFile("Skill/ThiefFloatAttack.lua")
DoFile("Skill/BoobyTrap.lua")
DoFile("Skill/BoobyTrap_Play.lua")
DoFile("Skill/melee_Use_TargetListModified.lua")
DoFile("Skill/EarthQuake.lua")
DoFile("Skill/SlidingTackle.lua")
DoFile("Skill/Iceberg.lua")
DoFile("Skill/Iceberg_Play.lua")
DoFile("Skill/DashDownBlow.lua")
DoFile("Skill/FloatDownBlow.lua")
DoFile("Skill/FloatDownShot.lua")
DoFile("Skill/SideDashAttack.lua")
DoFile("Skill/HommingMissile.lua")
DoFile("Skill/Roulette.lua")
DoFile("Skill/InstallDefault.lua")
DoFile("Skill/InstallDefault_Play.lua")
DoFile("Skill/Bomb_Explosion.lua")
DoFile("Skill/Resurrection01.lua")
DoFile("Skill/ResurrectCast.lua")
DoFile("Skill/Somersaultkick.lua")
DoFile("Skill/FinalDecision.lua")
DoFile("Skill/ScrewUpper.lua")
DoFile("Skill/JudgeDread.lua")
DoFile("Skill/SwiftAttack.lua")
DoFile("Skill/BugsLife.lua")
DoFile("Skill/Seven.lua")
DoFile("Skill/RollingLog_Play.lua")
DoFile("Skill/InstallSelf.lua")
DoFile("Skill/LightningSlash.lua")
DoFile("Skill/CarpetBombing.lua")
DoFile("Skill/CarpetBombing_Play.lua")
DoFile("Skill/GatlingRush.lua")
DoFile("Skill/WeaponBreak_Fire.lua")
DoFile("Skill/NineteenNinety.lua")
DoFile("Skill/ChainHurricaneKick.lua")
DoFile("Skill/SpiralCannon.lua")
DoFile("Skill/Santuary_Play.lua")
DoFile("Skill/UseUICall.lua")
DoFile("Skill/WyvernBlade.lua")
DoFile("Skill/Bro_Adogen_Fire.lua")
DoFile("Skill/DeathSnatch.lua")
DoFile("Skill/DeathSnatchFinish.lua")
DoFile("Skill/DeathSnatchHandMove.lua")
DoFile("Skill/RollingGround.lua")
DoFile("Skill/TimeFreeze.lua")
DoFile("Skill/Knight_BroSpin_Fire.lua")
DoFile("Skill/BroSpin_Fire.lua")
DoFile("Skill/Blink.lua")
DoFile("Skill/TwoActionFire.lua")
DoFile("Skill/Trap_Play.lua")
DoFile("Skill/Mon_S_Curve.lua")
DoFile("Skill/Mon_Touch_up.lua")
DoFile("Skill/Mon_Pull.lua")
DoFile("Skill/Mon_AirStrike.lua")

-- Pet Skill
DoFile("Skill/Pet/pet_melee_default.lua")
DoFile("Skill/Pet/pet_cloud_fire.lua")
DoFile("Skill/Pet/AIOnOff.lua")
DoFile("Skill/Pet/pet_mount.lua")
DoFile("Skill/Pet/call_trans.lua")
DoFile("Skill/Pet/pet_melee_riding.lua")

DoFile("Skill/Mon_Earthquake.lua")
DoFile("Skill/Mon_EnergyExplosion.lua")
DoFile("Skill/Mon_Rush.lua")
DoFile("Skill/Mon_Rush_Piercing.lua")
DoFile("Skill/Mon_Blocking.lua")
DoFile("Skill/Mon_MassiveProjectile.lua")
DoFile("Skill/Mon_MassiveProjectile2.lua")
DoFile("Skill/Mon_MassiveProjectile_Jump.lua")
DoFile("Skill/Mon_MassiveProjectile_Move.lua")
DoFile("Skill/Mon_360Degree_Shot.lua")
DoFile("Skill/Mon_SummonThorn.lua")
DoFile("Skill/Mon_SummonThorns.lua")
DoFile("Skill/Mon_BatMissile.lua")
DoFile("Skill/Mon_SummonThornSA.lua")
DoFile("Skill/Mon_SummonThornsSA.lua")
DoFile("Skill/Mon_DropProjectile.lua")
DoFile("Skill/Mon_DropProjectile_01.lua")
DoFile("Skill/Mon_Antares_Laser.lua")
DoFile("Skill/Mon_Patrol_Shot.lua")
DoFile("Skill/Mon_Breath.lua")
DoFile("Skill/Mon_RushAttack.lua")
DoFile("Skill/Mon_DieSkill.lua")
DoFile("Skill/Mon_Only_Ani.lua")
DoFile("Skill/Mon_Melee_Finish.lua")
DoFile("Skill/Mon_Shot_Around.lua")
DoFile("Skill/Mon_Shot_Around2.lua")
DoFile("Skill/Mon_Shot_Around_Finish.lua")
DoFile("Skill/Mon_Shot_Bidirection.lua")
DoFile("Skill/Mon_Teleport.lua")
DoFile("Skill/Mon_Shot_Sixshot.lua")
DoFile("Skill/Mon_Move.lua")
DoFile("Skill/mon_boss_die_movie.lua")
DoFile("Skill/mon_select_shot.lua")
DoFile("Skill/mon_select_shotbykey.lua")
DoFile("Skill/Mon_CrossAttack.lua")
DoFile("Skill/Mon_Melee_Delay.lua")
DoFile("Skill/Mon_Melee_Loop.lua")
DoFile("Skill/Fury_Camera.lua")

-- Magician Skill
DoFile("Skill/MagicMissile.lua")
DoFile("Skill/Magician/self_heal.lua")
DoFile("Skill/Magician/transformation.lua")
DoFile("Skill/Magician/burberrian.lua")
DoFile("Skill/MagicianShot.lua")
DoFile("Skill/MagicianFloatShot.lua")
DoFile("Skill/Magician_Charge_Laser.lua")
DoFile("Skill/MagicianDownShot.lua")
DoFile("Skill/MageDownShot.lua")
DoFile("Skill/Tornado.lua")
DoFile("Skill/BackDraft_Fire.lua")
DoFile("Skill/Snowblues_Play.lua")
DoFile("Skill/EnergyBall_Play.lua")
DoFile("Skill/Valcan300_Play.lua")

-- Archer Skill
--DoFile("Skill/Archer/Concent.lua")
--DoFile("Skill/Archer/CruelShot.lua")
--DoFile("Skill/Archer/DoubleShot.lua")
DoFile("Skill/Archer/Thrust.lua")
DoFile("Skill/Archer/Arrow_Shower.lua")
DoFile("Skill/Archer/Daepodong.lua")
DoFile("Skill/Archer/Cushion_Shot.lua")
DoFile("Skill/Double_Shot.lua")
DoFile("Skill/FalconBeat.lua")
DoFile("Skill/Blitz.lua")
DoFile("Skill/WolfRush.lua")
DoFile("Skill/MultipleShot.lua")
DoFile("Skill/ParticleCanon.lua")
DoFile("Skill/Raid.lua")
DoFile("Skill/RainOfFire.lua")
DoFile("Skill/Spark_Rock_Play.lua")

-- Master
DoFile("Skill/Master/Summon_Common.lua")
DoFile("Skill/Master/Summon_Common_Finish.lua")
DoFile("Skill/Master/Demolition_Bomber_idle.lua")
DoFile("Skill/Master/PhantomClone.lua")
DoFile("Skill/Master/PhantomWarrior_idle.lua")
DoFile("Skill/Master/PhantomNinja_idle.lua")
DoFile("Skill/Master/PhantomNinja_melee.lua")
DoFile("Skill/Master/Ice_Shower.lua")
DoFile("Skill/Master/Ice_ShowerSA.lua")
DoFile("Skill/Master/DeathStinger.lua")
DoFile("Skill/Master/DeathStingerSA.lua")
DoFile("Skill/Master/WarLord_SoulDrain.lua")
DoFile("Skill/Master/WarLord_SoulDrain_Ready.lua")
DoFile("Skill/Master/WarLord_SoulDrain_Finish.lua")
DoFile("Skill/Master/Skill_SoulDrain_play.lua")
DoFile("Skill/Master/WarLord_MagmaPiston.lua")
DoFile("Skill/Master/Skill_MagmaPiston_play.lua")
DoFile("Skill/Master/Skill_MagmaPiston_attack.lua")
DoFile("Skill/Master/Maniac_HellShout.lua")
DoFile("Skill/Master/Maniac_Marionette.lua")
DoFile("Skill/Master/Maniac_Marionette_Finish.lua")
DoFile("Skill/Master/Maniac_MarionetteSA.lua")
DoFile("Skill/Master/Shadow_ShadowBlade.lua")
DoFile("Skill/Master/Shadow_ShadowBladeSA.lua")
DoFile("Skill/Master/Shadow_ShadowBladeSAFinish.lua")
DoFile("Skill/Master/Skill_HellShout_play.lua")
DoFile("Skill/Master/DragonKnight_AscensionDragon.lua")
DoFile("Skill/Master/LightningMargnetSA.lua")
DoFile("Skill/Master/LightningMargnetPlay.lua")
DoFile("Skill/Master/Striker_SelfBomber.lua")
DoFile("Skill/Master/Striker_SelfBomber2.lua")
DoFile("Skill/Master/DragonKnight_DragonDive.lua")
DoFile("Skill/Master/DragonKnight_DragonDive_Finish.lua")
DoFile("Skill/Master/Sentinel_WindBlade.lua")
DoFile("Skill/Master/Sentinel_WindBladeSA.lua")
DoFile("Skill/Master/Arcmage_WrathOfHeaven.lua")
DoFile("Skill/Master/Arcmage_WrathOfHeavenSA.lua")
DoFile("Skill/Master/LightingStorm.lua")
DoFile("Skill/Master/LightingStorm_Finish.lua")
DoFile("Skill/Master/Skill_HealingWave.lua")
DoFile("Skill/Master/DemolitionCharge.lua")
DoFile("Skill/Master/DemolitionCharge1.lua")	--중간에 액션을 끊었을 때
DoFile("Skill/Master/DemolitionChargeSA.lua")
DoFile("Skill/Master/GroundZero_Creature_Idle.lua")
DoFile("Skill/Master/CrossBlade_Play.lua")
DoFile("Skill/Master/Nuclear.lua")
DoFile("Skill/Master/ReverseGravity.lua")
DoFile("Skill/Master/ReverseGravity2.lua")
DoFile("Skill/Master/ClubMania.lua")
DoFile("Skill/Master/ClubMania_Finish.lua")
DoFile("Skill/Master/AwakeCharge.lua")
DoFile("Skill/FriendShipBuff.lua")
DoFile("Skill/SharpShooting.lua")
DoFile("Skill/sniping.lua")
DoFile("Skill/FrozenShot_Play.lua")

DoFile("Skill/CmdBroadcast.lua")

--Sentinel
DoFile("Skill/Master/MultiStrape.lua")
DoFile("Skill/Master/MultiStrape_Fire.lua")
DoFile("Skill/Master/MultiStrape_Melee.lua")
DoFile("Skill/Master/Multistrape_Creature_idle.lua")

-- Sapphire Dragon's Skill
DoFile("Skill/Sapphire_Dragon/sp_attk_01.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_02.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_03.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_04.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_05.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_06.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_07.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_08.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_09.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_10.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_11.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_12.lua")
DoFile("Skill/Sapphire_Dragon/sp_attk_13.lua")
DoFile("Skill/Sapphire_Dragon/sp_appear.lua")
DoFile("Skill/Sapphire_Dragon/sp_damage.lua")
DoFile("Skill/Sapphire_Dragon/sp_die.lua")
DoFile("Skill/Sapphire_Dragon/crystal_appear.lua")

-- Parel's Skill
DoFile("Skill/Parel/parel_die.lua")
DoFile("Skill/Parel/parel_jumpattack.lua")


-- Fossil's Skill
DoFile("Skill/Lavalon/lv_appear.lua")
DoFile("Skill/Lavalon/lv_blaze.lua")
DoFile("Skill/Lavalon/lv_breath_c.lua")
DoFile("Skill/Lavalon/lv_breath_l.lua")
DoFile("Skill/Lavalon/lv_breath_r.lua")
DoFile("Skill/Lavalon/lv_die.lua")
DoFile("Skill/Lavalon/lv_dmg.lua")
DoFile("Skill/Lavalon/lv_powerbreak.lua")
DoFile("Skill/Lavalon/magiccannon_shot.lua")
DoFile("Skill/Lavalon/magiccannon_onlycast.lua")

-- laval hart skill
DoFile("Skill/Lavalon/lavalon_heart_die.lua")
DoFile("Skill/Lavalon/lavalon_heart_meteor.lua")
DoFile("Skill/Lavalon/lavalon_heart_meteor_blue.lua")

-- Aram Mutisha skill
DoFile("Skill/AramMutisha/Mutisha_InAram.lua")
DoFile("Skill/AramMutisha/Aram_Backward.lua")
DoFile("Skill/AramMutisha/Aram_Frontward.lua")
DoFile("Skill/AramMutisha/opening_movie.lua")
DoFile("Skill/AramMutisha/mutisha_die.lua")
DoFile("Skill/AramMutisha/ending_movie.lua")

-- Bone Dragon Skill
DoFile("Skill/BoneDragon/Mon_Twist.lua")
DoFile("Skill/BoneDragon/Mon_SummonBone.lua")
DoFile("Skill/BoneDragon/Mon_SummonBone_Play.lua")
DoFile("Skill/BoneDragon/Mon_DarkBreath.lua")
DoFile("Skill/BoneDragon/BoneDragon_Die.lua")
DoFile("Skill/BoneDragon/bonedragon_ending_movie.lua")
DoFile("Skill/BoneDragon/bonedragon_summon_monster.lua")
DoFile("Skill/BoneDragon/Mon_SummonBone2.lua")

-- Neve
DoFile("Skill/Neve/mon_target_loc_shot.lua")
DoFile("Skill/Neve/mon_multi_shot_byS.lua")

-- Paris
DoFile("Skill/Mon_Paris_Laser.lua")
DoFile("Skill/Mon_Paris_Laser_Multi.lua")

-- JobSkill
DoFile("Skill/JobSkill/JobSkill_Begin.lua")
DoFile("Skill/JobSkill/JobSkill_End.lua")

-- Manufacture
DoFile("Skill/Manufacture/Manufacture.lua")

-- DraClass Skill --
--Summoner 
DoFile("Skill/Sum_Rifle_Shot.lua")
DoFile("Skill/Sum_Rifle_ChargeShot.lua")
DoFile("Skill/Sum_Rifle_Jump_Shot.lua")
DoFile("Skill/Air_Sprash.lua")
DoFile("Skill/Sum_Summon.lua")
DoFile("Skill/Sum_Regain.lua")
DoFile("Skill/Sum_Recall.lua")
DoFile("Skill/Sum_Shout_of_Life.lua")
DoFile("Skill/Sum_Nature_Blessing.lua")
DoFile("Skill/Sum_Impact_Unsummon.lua")
DoFile("Skill/Air_Smash.lua")
DoFile("Skill/Sum_Rock_Punch.lua")
DoFile("Skill/Sum_Rolling_Attack.lua")

DoFile("Skill/bw_Z_3_2.lua")
-- elga
DoFile("Skill/Mon_RegenPointChoose.lua")