DoFile("WorldAction/WA_SAPHIREBOSS_APPEAR.lua")
DoFile("WorldAction/WA_SAPHIREBOSS_DIE.lua")
DoFile("WorldAction/WA_SB_ATTACK1.lua")
DoFile("WorldAction/WA_SB_ATTACK2.lua")
DoFile("WorldAction/WA_SB_ATTACK3.lua")
DoFile("WorldAction/WA_SB_ATTACK4.lua")
DoFile("WorldAction/WA_SB_ATTACK5.lua")
DoFile("WorldAction/WA_SB_ATTACK6.lua")
DoFile("WorldAction/WA_SB_ATTACK7.lua")
DoFile("WorldAction/WA_SB_ATTACK8.lua")
DoFile("WorldAction/WA_SB_CRYSTAL_APPEAR.lua")
DoFile("WorldAction/WA_SB_ROTATION.lua")
DoFile("WorldAction/WA_SB_DAMAGE.lua")
DoFile("WorldAction/WA_SB_ATTACK9.lua")
DoFile("WorldAction/WA_SB_ATTACK10.lua")

DoFile("WorldAction/Lavalon/WA_METEOR.lua")