#ifndef GM_GMSERVER_PGDBPROCESS_H
#define GM_GMSERVER_PGDBPROCESS_H

extern HRESULT CALLBACK OnDB_EXECUTE(CEL::DB_RESULT &rkResult);
extern HRESULT CALLBACK OnDB_EXECUTE_TRAN(CEL::DB_RESULT_TRAN &rkResult);

bool Q_DQT_SELECT_PETISION_DATA(CEL::DB_RESULT &rkResult);
bool Q_DQT_TRY_GMLOGIN(CEL::DB_RESULT &rkResult);
bool Q_DQT_SELECT_PETITION_DATA( CEL::DB_RESULT &rkResult );
bool Q_DQT_MODIFY_PETITION_DATA( CEL::DB_RESULT &rkResult );
bool Q_DQT_RECEIPT_PETITION( CEL::DB_RESULT &rkResult );			
bool Q_DQT_REMAINDER_PETITION( CEL::DB_RESULT &rkResult );		
bool Q_DQT_SELECT_PETITION_STATE( CEL::DB_RESULT &rkResult );

#endif // GM_GMSERVER_PGDBPROCESS_H