#ifndef WEAPON_XUI_XUI_COMMON_H
#define WEAPON_XUI_XUI_COMMON_H

#include <tchar.h>
#include "string"

#define XUI_USE_SCRIPT_CALL_OPTIMIZE

#define ROOT_DEF(id, real) std::wstring const ROOT_##id = _T(real);
#define ATTR_DEF(id, real) std::wstring const ATTR_##id = _T(real);


#ifdef XUI_USE_SCRIPT_CALL_OPTIMIZE
#define SCRIPT_DEF(id, real)	\
	std::wstring const SCRIPT_TEXT_##id = _T(real);	\
	unsigned int const SCRIPT_##id = __COUNTER__;
#else
#define SCRIPT_DEF(id, real) std::wstring const SCRIPT_##id = _T(real);
#endif


#define KEYWORD_DEF(id, real) std::wstring const KEYWORD_##id = _T(real);

ROOT_DEF(XUI,		"XUI")
ROOT_DEF(CONFIG,	"CONFIG");
ROOT_DEF(FORM,		"FORM")
ROOT_DEF(DUMMY,		"DUMMY")
ROOT_DEF(DIALOG,	"DIALOG")
ROOT_DEF(BUTTON,	"BUTTON")
ROOT_DEF(ANI_BAR,	"ANI_BAR")
ROOT_DEF(EDIT,		"EDIT")
ROOT_DEF(IMG,		"IMG")
ROOT_DEF(SCRIPT,	"SCRIPT")
ROOT_DEF(HOTKEY,	"HOTKEY")
ROOT_DEF(GLOBAL_HOTKEY, "GLOBAL_HOTKEY")
ROOT_DEF(ICON,		"ICON")
ROOT_DEF(BUILD,		"BUILD")
ROOT_DEF(CURSOR,	"CURSOR")
ROOT_DEF(MSG_BOX,	"MSG_BOX")
ROOT_DEF(EDIT_MULTI,	"EDIT_MULTI")
ROOT_DEF(HOTKEY_MODIFIER, "HOTKEY_MODIFIER")
ROOT_DEF(ATTR,		"ATTR")//속성 등록용 --> 이건 루트로 치지말지?
ROOT_DEF(LOCAL,		"LOCAL")// 로컬화 관련
ROOT_DEF(UNIQUE_CALL_TYPE, "UNIQUE_TYPE")

ROOT_DEF(TAB,			"TAB")
ROOT_DEF(TAB_ELEMENT,	"TAB_ELEMENT")
ROOT_DEF(TOOL_TIP,		"TOOL_TIP")
ROOT_DEF(WARNING,		"WARNING")
ROOT_DEF(WARNLIST,		"WARNLIST")

ROOT_DEF(LIST,			"LIST");
ROOT_DEF(LIST2,			"LIST2");
ROOT_DEF(TREE,			"TREE");
ROOT_DEF(CHECK_BUTTON,	"CHECK_BUTTON");

ROOT_DEF(STATIC_FORM,	"STATIC_FORM");
ROOT_DEF(UNIQUE_UI_TYPE_TO_ERRNO,	"UNIQUE_UI_TYPE_TO_ERRNO");

ROOT_DEF(HSCROLL, "HSCROLL");

ROOT_DEF(FULL_FORM, "FULL_FORM");


ATTR_DEF(ID,		"ID")
ATTR_DEF(X,			"X")
ATTR_DEF(Y,			"Y")
ATTR_DEF(Z,			"Z")
ATTR_DEF(W,			"W")
ATTR_DEF(H,			"H")
ATTR_DEF(HOT_KEY,	"HOT_KEY")
ATTR_DEF(INPUT_KEY_REAL,	"INPUT_KEY_REAL")
ATTR_DEF(ALIGN_X,	"ALIGN_X")
ATTR_DEF(ALIGN_Y,	"ALIGN_Y")
ATTR_DEF(IS_ABSOLUTE_X, "IS_ABSOLUTE_X")	// 해상도 상관없이 절대값 사용 할 것인가?
ATTR_DEF(IS_ABSOLUTE_Y, "IS_ABSOLUTE_Y")
ATTR_DEF(TEXT,		"TEXT")
ATTR_DEF(T_X,		"T_X")
ATTR_DEF(T_Y,		"T_Y")
ATTR_DEF(T_BOLD,	"T_BOLD")
ATTR_DEF(T_ITALIC,	"T_ITALIC")
ATTR_DEF(T_UNDERLINE,	"T_UNDERLINE")
ATTR_DEF(T_OUTLINE,	"T_OUTLINE")
ATTR_DEF(T_CENTER,	"T_CENTER")
ATTR_DEF(T_Y_CENTER,"T_Y_CENTER")
ATTR_DEF(T_RIGHT,	"T_RIGHT")
ATTR_DEF(FONT,		"FONT")
ATTR_DEF(U,			"U")
ATTR_DEF(V,			"V")
ATTR_DEF(UV_INDEX,	"UV_INDEX")	
ATTR_DEF(TOOL_TIP_TEXT,	"TOOL_TIP_TEXT")
ATTR_DEF(IGNORE_PARENT_RECT, "IGNORE_PARENT_RECT")
ATTR_DEF(NO_WORD_WRAP, "NO_WORD_WRAP")
ATTR_DEF(FONT_COLOR, "FONT_COLOR")
ATTR_DEF(FONT_COLOR_HEX, "FONT_COLOR_HEX")
ATTR_DEF(OUTLINE_COLOR_HEX, "OUTLINE_COLOR_HEX")
ATTR_DEF(ALPHA, "ALPHA")
ATTR_DEF(EFFECT, "EFFECT" )
ATTR_DEF(SPEED, "SPEED" )
ATTR_DEF(CALL_SOUND, "CALL_SOUND" )
ATTR_DEF(CLOSE_SOUND, "CLOSE_SOUND" )
ATTR_DEF(USE_INPUTTIME_CHECK, "USE_INPUTTIME_CHECK" )
ATTR_DEF(UNIQUE_EXIST_TYPE, "UNIQUE_EXIST_TYPE" )


//>>Modifier
ATTR_DEF(ADD_STR, "ADD_STR")
//<<Modifier

//>>UniqueExistUI
ATTR_DEF(ERR_NO, "ERR_NO")
ATTR_DEF(ERR_SOUND, "ERR_SOUND")

ATTR_DEF(ALIVE_TIME,	"ALIVE_TIME")
ATTR_DEF(ALIVE_TIME_IGNORE_MOUSE_OVER,	"ALIVE_TIME_IGNORE_MOUSE_OVER")
ATTR_DEF(TICK_TIME,		"TICK_TIME")

ATTR_DEF(CAN_DRAG,	"CAN_DRAG")
ATTR_DEF(CAN_CLIP,	"CAN_CLIP")
ATTR_DEF(CAN_COLOR_CHANGE,	"CAN_COLOR_CHANGE")
ATTR_DEF(PRIORITY,	"PRIORITY")
ATTR_DEF(USE_DRAW_RECT,	"USE_DRAW_RECT")

ATTR_DEF(USE_ALPHA_ANI,	"USE_ALPHA_ANI")
ATTR_DEF(IS_ENABLE,	"IS_ENABLE")
ATTR_DEF(IS_VISIBLE, "IS_VISIBLE")
ATTR_DEF(IS_CLOSED, "IS_CLOSED")
ATTR_DEF(IS_CHILD_DISPLAY, "IS_CHILD_DISPLAY")

ATTR_DEF(SCALE_CENTER_X, "SCALE_CENTER_X")
ATTR_DEF(SCALE_CENTER_Y, "SCALE_CENTER_Y")
ATTR_DEF(ROTATION_CENTER_X, "ROTATION_CENTER_X")
ATTR_DEF(ROTATION_CENTER_Y, "ROTATION_CENTER_Y")

ATTR_DEF(COLOR_TYPE, "COLOR_TYPE")
ATTR_DEF(IGNORE_TWINKLE, "IGNORE_TWINKLE")
ATTR_DEF(HIDE_OTHER, "HIDE_OTHER")
ATTR_DEF(NOT_HIDE, "NOT_HIDE")

ATTR_DEF(IMG,		"IMG")
ATTR_DEF(IMG_X,		"IMG_X")
ATTR_DEF(IMG_Y,		"IMG_Y")
ATTR_DEF(IMG_H,		"IMG_H")
ATTR_DEF(IMG_W,		"IMG_W")

ATTR_DEF(BTN_IMG,	"BTN_IMG")
ATTR_DEF(BTN_IMG_H,	"BTN_IMG_H")
ATTR_DEF(BTN_IMG_W,	"BTN_IMG_W")
ATTR_DEF(BTN_DOWN_IDX, "BTN_DOWN_IDX")
ATTR_DEF(BTN_UP_TEXT_COLOR, "BTN_UP_TEXT_COLOR")
ATTR_DEF(BTN_DOWN_TEXT_COLOR, "BTN_DOWN_TEXT_COLOR")
ATTR_DEF(BTN_OVER_TEXT_COLOR, "BTN_OVER_TEXT_COLOR")
ATTR_DEF(BTN_DIS_TEXT_COLOR, "BTN_DIS_TEXT_COLOR")
ATTR_DEF(BTN_ENABLE_CHANGE_COLOR, "BTN_ENABLE_CHANGE_COLOR")
ATTR_DEF(BTN_T_INVERTBOLD, "BTN_T_INVERTBOLD")
ATTR_DEF(BTN_T_COLOR_TYPE, "BTN_T_COLOR_TYPE")
ATTR_DEF(BTN_USE_TWINKLEIMG, "BTN_USE_TWINKLEIMG")
ATTR_DEF(BTN_SINGLE_IMAGE, "BTN_SINGLE_IMAGE")

ATTR_DEF(BTN_CLICK_LOCK, "BTN_CLICK_LOCK")
ATTR_DEF(BTN_VERTICAL_IMG, "BTN_VERTICAL_IMG")

ATTR_DEF(TAB_IMG,	"TAB_IMG")
ATTR_DEF(TAB_IMG_H,	"TAB_IMG_H")
ATTR_DEF(TAB_IMG_W,	"TAB_IMG_W")

ATTR_DEF(BAR_IMG,	"BAR_IMG")
ATTR_DEF(BAR_IMG_H,	"BAR_IMG_H")
ATTR_DEF(BAR_IMG_W,	"BAR_IMG_W")
ATTR_DEF(BAR_REVERSE, "BAR_REVERSE")
ATTR_DEF(BAR_IS_VERTICAL, "BAR_IS_VERTICAL")
ATTR_DEF(BTN_TYPE,	"BTN_TYPE")

//>에디트 전용
ATTR_DEF(EDIT_T_X,		"EDIT_T_X")
ATTR_DEF(EDIT_T_Y,		"EDIT_T_Y")
ATTR_DEF(EDIT_FONT,		"EDIT_FONT")
ATTR_DEF(EDIT_PREVIEW,	"EDIT_PREVIEW")
ATTR_DEF(EDIT_BLOCK_IMG, "EDIT_BLOCK_IMG")
ATTR_DEF(EDIT_CAROT_IMG, "EDIT_CAROT_IMG")
ATTR_DEF(EDIT_IS_SECRET, "EDIT_IS_SECRET")
ATTR_DEF(EDIT_EDITTING_DISABLE, "EDIT_EDITTING_DISABLE")
ATTR_DEF(EDIT_DONT_LOSTFOCUS, "EDIT_DONT_LOSTFOCUS")//포커스를 항상 잃지 않는다.
ATTR_DEF(EDIT_LIMIT_LENGTH, "EDIT_LIMIT_LENGTH")//최대 입력 글자수
ATTR_DEF(EDIT_ONLY_NUM, "EDIT_ONLY_NUM")//숫자모드
ATTR_DEF(EDIT_MULTI_LINE_COUNT, "EDIT_MULTI_LINE_COUNT")//멀티라인 카운트
ATTR_DEF(EDIT_ORDER_LANK, "EDIT_ORDER_LANK")
//<에디트 전용

//>AniBar 전용
//ATTR_DEF(BAR_COLOR,		"BAR_COLOR")
ATTR_DEF(BAR_COUNT,		"BAR_COUNT")
ATTR_DEF(BAR_TYPE,		"BAR_TYPE")
ATTR_DEF(BAR_IMG_MID_W,	"BAR_IMG_MID_W")
ATTR_DEF(BAR_SMOOTH,	"BAR_SMOOTH")
//<AniBar 전용

//>>Form
ATTR_DEF(NO_BG,		"NO_BG")
ATTR_DEF(USE_OFFSCREEN,		"USE_OFFSCREEN")
ATTR_DEF(PASS_EVENT,		"PASS_EVENT")
ATTR_DEF(NO_FOCUS,	"NO_FOCUS")
ATTR_DEF(TYPING_EFFECT, "TYPING_EFFECT")
// <<Form

//>>DIALOG
ATTR_DEF(TITLE,			"TITLE")
ATTR_DEF(TITLE_FONT,	"TITLE_FONT")
ATTR_DEF(TITLE_T_X,		"TITLE_T_X")
ATTR_DEF(TITLE_T_Y,		"TITLE_T_Y")
// <<DIALOG

// >>ICON
ATTR_DEF(ICON_GRP,		"ICON_GRP")
ATTR_DEF(ICON_KEY,		"ICON_KEY")
ATTR_DEF(ICON_STATIC,	"ICON_STATIC")//드래그 안되고 고정된 아이콘
// <<ICON

//>>Build
ATTR_DEF(TARGET_ID,		"TARGET_ID")
ATTR_DEF(X_COUNT,		"X_COUNT")
ATTR_DEF(Y_COUNT,		"Y_COUNT")
ATTR_DEF(X_GAB,			"X_GAB")
ATTR_DEF(Y_GAB,			"Y_GAB")
ATTR_DEF(START_INDEX,	"START_INDEX")
ATTR_DEF(TRG_CUSTOME_ID, "TRG_CUSTOME_ID")
ATTR_DEF(IS_RESERVE,	"IS_RESERVE")
//<<Build

//리스트 전용
//ATTR_DEF(ITEM_COUNT,			"ITEM_COUNT")
//ATTR_DEF(DISPLAY_COUNT,		"DISPLAY_COUNT")
ATTR_DEF(ITEM_X,					"ITEM_X")
ATTR_DEF(ITEM_Y,					"ITEM_Y")
ATTR_DEF(ITEM_WIDTH,				"ITEM_WIDTH")
ATTR_DEF(ITEM_HEIGHT,				"ITEM_HEIGHT")
ATTR_DEF(SCROLL_VALUE,				"SCROLL_VALUE")
ATTR_DEF(IGNORE_BTN_PARENTRECT,		"IGNORE_BTN_PARENTRECT")

//ATTR_DEF(CAN_SELECT,			"CAN_SELECT")

ATTR_DEF(BTN_UP,				"BTN_UP")
ATTR_DEF(BTN_DOWN,				"BTN_DOWN")
ATTR_DEF(BTN_MIDDLE,			"BTN_MIDDLE")
ATTR_DEF(WND_BAR,				"WND_BAR")
ATTR_DEF(ELEMENT_ID,			"ELEMENT_ID")

ATTR_DEF(EXPENSION_BTN_IMG,	"EXPENSION_BTN_IMG")
ATTR_DEF(EXP_BTN_W, "EXP_BTN_W")
ATTR_DEF(EXP_BTN_H, "EXP_BTN_H")
ATTR_DEF(EXP_BTN_X, "EXP_BTN_X")
ATTR_DEF(EXP_BTN_Y, "EXP_BTN_Y")
ATTR_DEF(EXP_BTN_IMG_W, "EXP_BTN_IMG_W")
ATTR_DEF(EXP_BTN_IMG_H, "EXP_BTN_IMG_H")
ATTR_DEF(EXP_COLOR_CHANGE, "EXP_COLOR_CHANGE")
ATTR_DEF(EXP_COLOR_TYPE, "EXP_COLOR_TYPE")

//HSCROLL 용
ATTR_DEF(BTN, "BTN")
ATTR_DEF(MIN, "MIN")
ATTR_DEF(MAX, "MAX")
ATTR_DEF(CUR, "CUR")

//----->Static Form
ATTR_DEF(IMG_BODY,		"IMG_BODY")
ATTR_DEF(IMG_TB,		"IMG_TB")
ATTR_DEF(IMG_LR,		"IMG_LR")
ATTR_DEF(IMG_CORNER,	"IMG_CORNER")
ATTR_DEF(BODY_W,		"BODY_W")
ATTR_DEF(BODY_H,		"BODY_H")
ATTR_DEF(TB_W,			"TB_W")
ATTR_DEF(TB_H,			"TB_H")
ATTR_DEF(LR_W,			"LR_W")
ATTR_DEF(LR_H,			"LR_H")
ATTR_DEF(CORNER_W,		"CORNER_W")
ATTR_DEF(CORNER_H,		"CORNER_H")

ATTR_DEF(STATIC_NUM,	"STATIC_NUM")
//<-----Static Form

//----->Config
ATTR_DEF(SOUND_L_BTN_DOWN_0,	"SOUND_L_BTN_DOWN_0")
ATTR_DEF(SOUND_R_BTN_DOWN_0,	"SOUND_R_BTN_DOWN_0")
ATTR_DEF(SOUND_MOUSE_OVER_0,	"SOUND_MOUSE_OVER_0")

ATTR_DEF(SOUND_L_BTN_DOWN_1,	"SOUND_L_BTN_DOWN_1")
ATTR_DEF(SOUND_R_BTN_DOWN_1,	"SOUND_R_BTN_DOWN_1")
ATTR_DEF(SOUND_MOUSE_OVER_1,	"SOUND_MOUSE_OVER_1")

ATTR_DEF(SOUND_L_BTN_DOWN_2,	"SOUND_L_BTN_DOWN_2")
ATTR_DEF(SOUND_R_BTN_DOWN_2,	"SOUND_R_BTN_DOWN_2")
ATTR_DEF(SOUND_MOUSE_OVER_2,	"SOUND_MOUSE_OVER_2")

ATTR_DEF(SOUND_L_BTN_DOWN_3,	"SOUND_L_BTN_DOWN_3")
ATTR_DEF(SOUND_R_BTN_DOWN_3,	"SOUND_R_BTN_DOWN_3")
ATTR_DEF(SOUND_MOUSE_OVER_3,	"SOUND_MOUSE_OVER_3")

ATTR_DEF(SOUND_L_BTN_DOWN_4,	"SOUND_L_BTN_DOWN_4")
ATTR_DEF(SOUND_R_BTN_DOWN_4,	"SOUND_R_BTN_DOWN_4")
ATTR_DEF(SOUND_MOUSE_OVER_4,	"SOUND_MOUSE_OVER_4")

ATTR_DEF(SOUND_L_BTN_DOWN_5,	"SOUND_L_BTN_DOWN_5")
ATTR_DEF(SOUND_R_BTN_DOWN_5,	"SOUND_R_BTN_DOWN_5")
ATTR_DEF(SOUND_MOUSE_OVER_5,	"SOUND_MOUSE_OVER_5")

ATTR_DEF(TOOL_TIP_IMG_BODY, "TOOL_TIP_IMG_BODY")
ATTR_DEF(TOOL_TIP_IMG_TOP_BOTTOM, "TOOL_TIP_IMG_TOP_BOTTOM")
ATTR_DEF(TOOL_TIP_IMG_LEFR_RIGHT, "TOOL_TIP_IMG_LEFR_RIGHT")
ATTR_DEF(TOOL_TIP_IMG_CORNER, "TOOL_TIP_IMG_CORNER")
ATTR_DEF(TOOL_TIP_IMG_LOCK, "TOOL_TIP_IMG_LOCK")
ATTR_DEF(TOOL_TIP_IMG_CLOSE, "TOOL_TIP_IMG_CLOSE")

ATTR_DEF(BTN_UP_TEXT_COLOR_DFT, "BTN_UP_TEXT_COLOR_DFT")
ATTR_DEF(BTN_DOWN_TEXT_COLOR_DFT, "BTN_DOWN_TEXT_COLOR_DFT")
ATTR_DEF(BTN_OVER_TEXT_COLOR_DFT, "BTN_OVER_TEXT_COLOR_DFT")
ATTR_DEF(BTN_DIS_TEXT_COLOR_DFT, "BTN_DIS_TEXT_COLOR_DFT")

#define ATTR_DEF_S(id, real) ATTR_DEF(id, #real);
#define ATTR_BTN_T_COLOR_SET(index)	\
	ATTR_DEF_S(BTN_UP_TEXT_COLOR_##index,	BTN_UP_TEXT_COLOR_##index)\
	ATTR_DEF_S(BTN_DOWN_TEXT_COLOR_##index,	BTN_DOWN_TEXT_COLOR_##index)\
	ATTR_DEF_S(BTN_OVER_TEXT_COLOR_##index,	BTN_OVER_TEXT_COLOR_##index)\
	ATTR_DEF_S(BTN_DIS_TEXT_COLOR_##index,	BTN_DIS_TEXT_COLOR_##index)\

ATTR_BTN_T_COLOR_SET(0)
ATTR_BTN_T_COLOR_SET(1)
ATTR_BTN_T_COLOR_SET(2)
ATTR_BTN_T_COLOR_SET(3)
ATTR_BTN_T_COLOR_SET(4)
ATTR_BTN_T_COLOR_SET(5)
ATTR_BTN_T_COLOR_SET(6)
ATTR_BTN_T_COLOR_SET(7)
ATTR_BTN_T_COLOR_SET(8)
ATTR_BTN_T_COLOR_SET(9)
ATTR_BTN_T_COLOR_SET(10)
ATTR_BTN_T_COLOR_SET(11)
ATTR_BTN_T_COLOR_SET(12)
ATTR_BTN_T_COLOR_SET(13)
ATTR_BTN_T_COLOR_SET(14)
ATTR_BTN_T_COLOR_SET(15)
ATTR_BTN_T_COLOR_SET(16)
ATTR_BTN_T_COLOR_SET(17)
ATTR_BTN_T_COLOR_SET(18)
ATTR_BTN_T_COLOR_SET(19)
ATTR_BTN_T_COLOR_SET(20)
ATTR_BTN_T_COLOR_SET(21)
ATTR_BTN_T_COLOR_SET(22)
ATTR_BTN_T_COLOR_SET(23)
ATTR_BTN_T_COLOR_SET(24)
ATTR_BTN_T_COLOR_SET(25)
ATTR_BTN_T_COLOR_SET(26)
ATTR_BTN_T_COLOR_SET(27)
ATTR_BTN_T_COLOR_SET(28)
ATTR_BTN_T_COLOR_SET(29)
ATTR_BTN_T_COLOR_SET(30)


/*ATTR_DEF(BTN_UP_TEXT_COLOR_0, "BTN_UP_TEXT_COLOR_0")
ATTR_DEF(BTN_DOWN_TEXT_COLOR_0, "BTN_DOWN_TEXT_COLOR_0")
ATTR_DEF(BTN_OVER_TEXT_COLOR_0, "BTN_OVER_TEXT_COLOR_0")
ATTR_DEF(BTN_DIS_TEXT_COLOR_0, "BTN_DIS_TEXT_COLOR_0")

ATTR_DEF(BTN_UP_TEXT_COLOR_1, "BTN_UP_TEXT_COLOR_1")
ATTR_DEF(BTN_DOWN_TEXT_COLOR_1, "BTN_DOWN_TEXT_COLOR_1")
ATTR_DEF(BTN_OVER_TEXT_COLOR_1, "BTN_OVER_TEXT_COLOR_1")
ATTR_DEF(BTN_DIS_TEXT_COLOR_1, "BTN_DIS_TEXT_COLOR_1")

ATTR_DEF(BTN_UP_TEXT_COLOR_1, "BTN_UP_TEXT_COLOR_2")
ATTR_DEF(BTN_DOWN_TEXT_COLOR_1, "BTN_DOWN_TEXT_COLOR_2")
ATTR_DEF(BTN_OVER_TEXT_COLOR_1, "BTN_OVER_TEXT_COLOR_2")
ATTR_DEF(BTN_DIS_TEXT_COLOR_1, "BTN_DIS_TEXT_COLOR_2")*/


#define ATTR_STATIC_SET(index)	\
	ATTR_DEF_S(IMG_BODY_##index,	IMG_BODY_##index)\
	ATTR_DEF_S(IMG_TB_##index,		IMG_TB_##index)\
	ATTR_DEF_S(IMG_LR_##index,		IMG_LR_##index)\
	ATTR_DEF_S(IMG_CORNER_##index,	IMG_CORNER_##index)\
	ATTR_DEF_S(BODY_W_##index,		BODY_W_##index)\
	ATTR_DEF_S(BODY_H_##index,		BODY_H_##index)\
	ATTR_DEF_S(TB_W_##index,		TB_W_##index)\
	ATTR_DEF_S(TB_H_##index,		TB_H_##index)\
	ATTR_DEF_S(LR_W_##index,		LR_W_##index)\
	ATTR_DEF_S(LR_H_##index,		LR_H_##index)\
	ATTR_DEF_S(CORNER_W_##index,	CORNER_W_##index)\
	ATTR_DEF_S(CORNER_H_##index,	CORNER_H_##index)//아래를 만든다.
	//ATTR_DEF(IMG_BODY_1,	"IMG_BODY_1")
	//ATTR_DEF(IMG_TB_1,		"IMG_TB_1")
	//ATTR_DEF(IMG_LR_1,		"IMG_LR_1")
	//ATTR_DEF(IMG_CORNER_1,	"IMG_CORNER_1")
	//ATTR_DEF(BODY_W_1,		"BODY_W_1")
	//ATTR_DEF(BODY_H_1,		"BODY_H_1")
	//ATTR_DEF(TB_W_1,		"TB_W_1")
	//ATTR_DEF(TB_H_1,		"TB_H_1")
	//ATTR_DEF(LR_W_1,		"LR_W_1")
	//ATTR_DEF(LR_H_1,		"LR_H_1")
	//ATTR_DEF(CORNER_W_1,	"CORNER_W_1")
	//ATTR_DEF(CORNER_H_1,	"CORNER_H_1")

ATTR_STATIC_SET(1)
ATTR_STATIC_SET(2)
ATTR_STATIC_SET(3)
ATTR_STATIC_SET(4)
ATTR_STATIC_SET(5)
ATTR_STATIC_SET(6)
ATTR_STATIC_SET(7)
ATTR_STATIC_SET(8)
ATTR_STATIC_SET(9)
ATTR_STATIC_SET(10)
ATTR_STATIC_SET(11)
ATTR_STATIC_SET(12)
ATTR_STATIC_SET(13)
ATTR_STATIC_SET(14)
ATTR_STATIC_SET(15)
ATTR_STATIC_SET(16)
ATTR_STATIC_SET(17)
ATTR_STATIC_SET(18)
ATTR_STATIC_SET(19)
ATTR_STATIC_SET(20)
ATTR_STATIC_SET(21)
ATTR_STATIC_SET(22)
ATTR_STATIC_SET(23)
ATTR_STATIC_SET(24)
ATTR_STATIC_SET(25)
ATTR_STATIC_SET(26)
ATTR_STATIC_SET(27)
ATTR_STATIC_SET(28)
ATTR_STATIC_SET(29)
ATTR_STATIC_SET(30)
ATTR_STATIC_SET(31)
ATTR_STATIC_SET(32)
ATTR_STATIC_SET(33)
ATTR_STATIC_SET(34)
ATTR_STATIC_SET(35)
ATTR_STATIC_SET(36)
ATTR_STATIC_SET(37)
ATTR_STATIC_SET(38)
ATTR_STATIC_SET(39)
ATTR_STATIC_SET(40)
ATTR_STATIC_SET(41)
ATTR_STATIC_SET(42)
ATTR_STATIC_SET(43)
ATTR_STATIC_SET(44)
ATTR_STATIC_SET(45)
ATTR_STATIC_SET(46)
ATTR_STATIC_SET(47)
ATTR_STATIC_SET(48)
ATTR_STATIC_SET(49)

//<-----Config

SCRIPT_DEF(ON_ACTIVATE,	"ON_ACTIVATE")
SCRIPT_DEF(ON_CREATE,	"ON_CREATE")
SCRIPT_DEF(ON_FOCUS,	"ON_FOCUS")						//EditBox에 한하여 Focus를 가질때 (ON_FOCUS, SCRIPT_ON_FOCUS)
SCRIPT_DEF(ON_CALL,	"ON_CALL")
SCRIPT_DEF(ON_CLOSE,	"ON_CLOSE")
SCRIPT_DEF(ON_ALIVE_TIME_END, "ON_ALIVE_TIME_END")
SCRIPT_DEF(ON_CORRECT,	"ON_CORRECT")

SCRIPT_DEF(ON_L_BTN_UP,		"ON_L_BTN_UP")
SCRIPT_DEF(ON_L_BTN_DOWN,	"ON_L_BTN_DOWN")
SCRIPT_DEF(ON_L_BTN_DBL_DOWN,	"ON_L_BTN_DBL_DOWN")
SCRIPT_DEF(ON_R_BTN_UP,		"ON_R_BTN_UP")
SCRIPT_DEF(ON_R_BTN_DOWN,	"ON_R_BTN_DOWN")

SCRIPT_DEF(ON_KEY_ENTER,	"ON_KEY_ENTER")//IME와 XUI_Edit관련 전용 이벤트
SCRIPT_DEF(ON_KEY_TAB,		"ON_KEY_TAB")//IME와 XUI_Edit관련 전용 이벤트
SCRIPT_DEF(ON_KEY_UP,		"ON_KEY_UP")//IME와 XUI_Edit관련 전용 이벤트
SCRIPT_DEF(ON_KEY_DOWN,		"ON_KEY_DOWN")//IME와 XUI_Edit관련 전용 이벤트
SCRIPT_DEF(ON_MOUSE_OVER,		"ON_MOUSE_OVER")
SCRIPT_DEF(ON_MOUSE_OUT,		"ON_MOUSE_OUT")
SCRIPT_DEF(ON_MOUSE_MOVE,		"ON_MOUSE_MOVE")

SCRIPT_DEF(ON_BAR_FULL,		"ON_BAR_FULL")
SCRIPT_DEF(ON_BAR_CLOSE,	"ON_BAR_CLOSE")
SCRIPT_DEF(ON_TICK,			"ON_TICK")
SCRIPT_DEF(ON_BUILD,		"ON_BUILD")
SCRIPT_DEF(ON_DISPLAY,		"ON_DISPLAY")

SCRIPT_DEF(ON_AFTER_DISPLAY,	"ON_AFTER_DISPLAY")
SCRIPT_DEF(ON_OUT_DISPLAY,	"ON_OUT_DISPLAY")
SCRIPT_DEF(ON_AFTER_L_BTN_UP,	"ON_AFTER_L_BTN_UP")
SCRIPT_DEF(ON_AFTER_R_BTN_UP,	"ON_AFTER_R_BTN_UP")
SCRIPT_DEF(ON_WHEEL_UP,		"ON_WHEEL_UP")

SCRIPT_DEF(ON_WHEEL_DOWN,	"ON_WHEEL_DOWN")	
SCRIPT_DEF(ON_SCROLL_MOVE,	"ON_SCROLL_MOVE")
SCRIPT_DEF(ON_SCROLL_VALUE_CHANGED, "ON_SCROLL_VALUE_CHANGED")
SCRIPT_DEF(ON_GET_FOCUS,	"ON_GET_FOCUS")
SCRIPT_DEF(ON_LOSE_FOCUS,	"ON_LOSE_FOCUS")
SCRIPT_DEF(ON_PICK_UP,		"ON_PICK_UP")
//
// 여기에 추가, 추가하면 xui_wnd.cpp 에도 추가해 줘야 함.

//
SCRIPT_DEF(MAX_NUM,	"MAX_NUM")		// MAX number Definition을 위한 설정.

KEYWORD_DEF(TITLE_BAR,		"DLG_TITLE_BAR");
KEYWORD_DEF(FORM_BG,		"FORM_BG");
KEYWORD_DEF(TITLE_BTN_EXIT,	"DLG_TITLE_BTN_EXIT");
KEYWORD_DEF(TITLE_BTN_MIN,	"DLG_TITLE_BTN_MIN");

std::wstring const STR_XUI_CURSOR = _T("CURSOR");

size_t const HEIGHT_TITLE_BAR	= 20;
size_t const WIDTH_TITLE_BTN	= 20;
size_t const HEIGHT_TITLE_BTN	= HEIGHT_TITLE_BAR;
float const DEFAULT_ALPHA	= 0.20f;
float const ALPHA_INC		= 0.20f;
float const ALPHA_MAX		= 1.00f;

size_t const BUTTON_STATE_NUM = 6;

#endif // WEAPON_XUI_XUI_COMMON_H