#ifndef CONTENTS_CONTENTSSERVER_ITEM_PGDBPROCESS_H
#define CONTENTS_CONTENTSSERVER_ITEM_PGDBPROCESS_H

#include "Variant/PgDBCache.h"

extern HRESULT CALLBACK OnDB_EXECUTE_Item(CEL::DB_RESULT &rkResult);
extern HRESULT CALLBACK OnDB_EXECUTE_TRAN_Item(CEL::DB_RESULT_TRAN &rkResult);

extern bool InitDB();

extern bool Q_DQT_CLEAR_CONNECTION_CHANNEL(CEL::DB_RESULT &rkResult);
extern HRESULT Q_DQT_SAVE_PLAYER_EFFECT(CEL::DB_RESULT &rkResult);
extern HRESULT Q_DQT_CASH_TRAN_COMMIT(CEL::DB_RESULT &rkResult);
extern HRESULT Q_DQT_CASH_TRANSACTION(CEL::DB_RESULT &rkResult);

#endif // CONTENTS_CONTENTSSERVER_ITEM_PGDBPROCESS_H