//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ServerControl.rc
//
#define IDSEND                          2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SERVERCONTROL_DIALOG        102
#define IDD_GENERALDLG                  103
#define IDR_MAINFRAME                   128
#define IDB_HDRUP                       129
#define IDB_HDRDOWN                     130
#define IDI_STATE_O                     132
#define IDI_ICON1                       133
#define IDI_STATE_X                     134
#define IDI_ICON2                       135
#define IDR_MENU1                       136
#define IDR_MAIN_MENU                   136
#define IDR_MENU2                       137
#define IDB_BITMAP1                     138
#define IDD_SERVER_ON_DLG               139
#define IDD_FILE_DOWN_DLG               140
#define IDD_CHANGE_MAX_USER_DLG         141
#define IDD_NOTICE_DLG                  142
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_LIST_SERVER                 1002
#define IDC_BUTTON1                     1003
#define IDC_BTN_CLOSE                   1003
#define IDC_BUTTON2                     1004
#define IDC_BTN_CONNECT                 1004
#define IDC_BTN_REFRESH                 1005
#define IDC_TREE1                       1006
#define IDC_BTN_REFRESH2                1006
#define IDC_BTN_PATCH                   1006
#define IDC_BTN_RESYNC                  1006
#define IDC_BTN_ON                      1007
#define IDC_BTN_OFF                     1008
#define IDC_EDIT_REFRESH_TIME           1009
#define IDC_BTN_RECV_LOG_DATE           1009
#define IDC_BTN_NOTICE                  1009
#define IDC_BTN_OFF2                    1010
#define IDC_BTN_PROCESSKILL             1010
#define IDC_BTN_ON2                     1011
#define IDC_CHECK_USEBEEP               1011
#define IDC_BTN_RECV_LOG_ALL            1011
#define IDC_EDIT_LOG                    1012
#define IDC_BUTTON3                     1013
#define IDC_BTN_LOG_CLEAR               1013
#define IDC_BTN_PATCH2                  1013
#define IDC_CONFIRM_KILL                1014
#define IDC_CONFIRM_RESYNC              1015
#define IDC_CONFIRM_KILL2               1016
#define IDC_BUTTON5                     1017
#define IDC_CONFIRM_KILL3               1017
#define IDD_TreeView                    1018
#define IDC_CONFIRM_KILL4               1019
#define IDC_BTN_RECV_LOG_ALL2           1020
#define IDC_BTN_RECV_LOG_ALL3           1021
#define IDC_SERVER_ITEM                 1022
#define IDC_CONFIRM_KILL5               1022
#define IDC_NAME                        1023
#define IDC_TEXT                        1023
#define IDC_BTN_REFRESH3                1023
#define IDC_BTN_ON3                     1023
#define IDC_CHECK                       1023
#define IDC_BTN_OFF3                    1024
#define IDC_STATIC_VIEW                 1026
#define IDC_DISP_1                      1027
#define IDC_DISP_2                      1028
#define IDC_DISP_3                      1029
#define IDC_DISP_4                      1030
#define IDC_DATETIMEPICKER1             1031
#define IDC_DATETIMEPICKER2             1032
#define IDC_BTN_OFF4                    1033
#define IDC_BTN_SELECT_ALL              1034
#define IDC_BTN_SELECT_ROOT             1035
#define IDC_TAB4                        1036
#define IDC_CAUTION_TEXT                1037
#define IDC_BTN_SELECT_ROOT2            1037
#define IDC_BTN_SELECT_REALM            1037
#define IDC_INFO_TEXT                   1038
#define IDC_TEXT_HACK                   1039
#define IDC_HACK_TEXT                   1039
#define IDC_DUMP_TEXT                   1040
#define IDC_TEXT_LIST_INFO              1041
#define IDC_PROGRESS2                   1043
#define IDC_PROGRESS3                   1044
#define IDC_JOB_PROGRESS                1044
#define IDC_RADIO1                      1045
#define IDC_RADIO2                      1046
#define IDC_CHECK1                      1047
#define IDC_CHECK2                      1048
#define IDC_GROUP_MAX_USER              1050
#define IDC_GROUP_RESYNC                1051
#define IDC_GROUP_TERMINATE             1052
#define IDC_GROUP_DOWNLOAD              1053
#define IDC_TEXT_FILE_NAME              1054
#define IDC_TEXT_FILE_SIZE              1055
#define IDC_GROUP_SERVER_SWITCH         1056
#define IDC_LIST1                       1057
#define IDC_TEXT_FILE_COUNT             1057
#define IDC_STATIC_TOTAL_INFO           1058
#define IDC_GROUP_PROCESS               1058
#define IDC_GROUP_OPTION                1059
#define IDC_GROUP_MAX_USER2             1059
#define IDC_STATIC_PERIOD               1060
#define IDC_GROUP_TYPE                  1061
#define IDC_TEXT_CCU                    1062
#define IDC_TEXT_BEFORE_COUNT           1064
#define IDC_EDIT_MAX_USER               1065
#define IDC_TEXT_PROCESS                1067
#define IDC_COMBO_REALM                 1068
#define IDC_COMBO_CHANNEL               1069
#define ID_FILE_NEW32771                32771
#define ID_NETWORK_SERVERON             32772
#define ID_NETWORK_SERVEROFF            32773
#define ID_NETWORK_PROCESSKILL          32774
#define ID_NETWORK_REFRESH              32775
#define ID_NETWORK_CONNECT              32776
#define ID_NETWORK_DISCONNECT           32777
#define ID_FILE_EXIT                    32778
#define ID_COMMAND_ON                   32779
#define ID_COMMAND_OFF                  32780
#define ID_COMMAND_TERMINATE            32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
