#ifndef CENTER_CENTERSERVER_MAINFRAME_PGKEYEVENT_H
#define CENTER_CENTERSERVER_MAINFRAME_PGKEYEVENT_H

extern bool RegistKeyEvent();
extern bool CALLBACK OnTerminateServer(WORD const& rkInputKey);

#endif // CENTER_CENTERSERVER_MAINFRAME_PGKEYEVENT_H