#ifndef CONTENTS_CONTENTSSERVER_MAINFRAME_PGKEYEVENT_H
#define CONTENTS_CONTENTSSERVER_MAINFRAME_PGKEYEVENT_H

extern bool RegistKeyEvent();
extern bool CALLBACK OnTerminateServer(WORD const& rkInputKey);

#endif // CONTENTS_CONTENTSSERVER_MAINFRAME_PGKEYEVENT_H