#ifndef CONTENTS_CONTENTSSERVER_ETC_PGSOCIALDBUTIL_H
#define CONTENTS_CONTENTSSERVER_ETC_PGSOCIALDBUTIL_H

namespace SocialDBUtil
{
	void ProcessPacket(BM::Stream::DEF_STREAM_TYPE const wType, BM::Stream& rkPacket);
}

#endif // CONTENTS_CONTENTSSERVER_ETC_PGSOCIALDBUTIL_H