#ifndef IMMIGRATION_IMMIGRATIONSERVER_DATABASE_PGDBPROCESS_H
#define IMMIGRATION_IMMIGRATIONSERVER_DATABASE_PGDBPROCESS_H

#include "stdafx.h"

bool LoadDB();
HRESULT CALLBACK OnDB_EXECUTE(CEL::DB_RESULT &rkResult);
HRESULT CALLBACK OnDB_EXECUTE_TRAN(CEL::DB_RESULT_TRAN &);

#endif // IMMIGRATION_IMMIGRATIONSERVER_DATABASE_PGDBPROCESS_H