#ifndef IMMIGRATION_IMMIGRATIONSERVER_MAINFRAME_PGKEYEVENT_H
#define IMMIGRATION_IMMIGRATIONSERVER_MAINFRAME_PGKEYEVENT_H

extern bool RegistKeyEvent();
extern bool CALLBACK OnTerminateServer(WORD const& wExitCode);
extern bool CALLBACK OnCleanupService(WORD const& wExitCode);

#endif // IMMIGRATION_IMMIGRATIONSERVER_MAINFRAME_PGKEYEVENT_H