#ifndef IMMIGRATION_IMMGRATIONSERVER_MAINFRAME_PGTIMER_H
#define IMMIGRATION_IMMGRATIONSERVER_MAINFRAME_PGTIMER_H

extern void CALLBACK Timer20s(DWORD dwUserData);
extern void CALLBACK Timer_10s(DWORD dwUserData);

#endif // IMMIGRATION_IMMGRATIONSERVER_MAINFRAME_PGTIMER_H