#ifndef IMMIGRATION_IMMIGRATIONSERVER_NETWORK_RECVFROMCONSENT_H
#define IMMIGRATION_IMMIGRATIONSERVER_NETWORK_RECVFROMCONSENT_H

extern bool OnRecvFromConsent(CEL::CSession_Base * const pkSession, WORD const wkType, BM::Stream * const pkPacket);

#endif // IMMIGRATION_IMMIGRATIONSERVER_NETWORK_RECVFROMCONSENT_H