/////////////// COMMON Version
#define VERSION_PRODUCTVERSION_NUM	3.3.11.0
#define VERSION_PRODUCTVERSION_STR	"3.3.11.0"
#define VERSION_PRIVATE_BUILD		"2022.05.26.01"

//////////////// DRAGONICA Client Information
#define VERSION_FILEVERSION_CLIENT_NUM		3.3.11.0
#define VERSION_FILEVERSION_CLIENT_STR		"3.3.11.0"

//////////////// DRAGONICA Server Information
#define VERSION_FILEVERSION_CENTER_NUM		3.3.11.0
#define VERSION_FILEVERSION_CENTER_STR		"3.3.11.0"

#define VERSION_FILEVERSION_CONTENTS_NUM	3.3.11.0
#define VERSION_FILEVERSION_CONTENTS_STR	"3.3.11.0"

#define VERSION_FILEVERSION_GM_NUM			3.3.11.0
#define VERSION_FILEVERSION_GM_STR			"3.3.11.0"

//#define VERSION_FILEVERSION_ITEM_NUM		3.3.11.0
//#define VERSION_FILEVERSION_ITEM_STR		"3.3.11.0"

#define VERSION_FILEVERSION_LOG_NUM			3.3.11.0
#define VERSION_FILEVERSION_LOG_STR			"3.3.11.0"

#define VERSION_FILEVERSION_LOGIN_NUM		3.3.11.0
#define VERSION_FILEVERSION_LOGIN_STR		"3.3.11.0"

//#define VERSION_FILEVERSION_MACHINE_NUM		3.3.11.0
//#define VERSION_FILEVERSION_MACHINE_STR		"3.3.11.0"

#define VERSION_FILEVERSION_MAP_NUM			3.3.11.0
#define VERSION_FILEVERSION_MAP_STR			"3.3.11.0"

#define VERSION_FILEVERSION_SWITCH_NUM		3.3.11.0
#define VERSION_FILEVERSION_SWITCH_STR		"3.3.11.0"

#define VERSION_FILEVERSION_IMM_NUM		3.3.11.0
#define VERSION_FILEVERSION_IMM_STR		"3.3.11.0"

#define VERSION_FILEVERSION_MMC_NUM		3.3.11.0
#define VERSION_FILEVERSION_MMC_STR		"3.3.11.0"

#define VERSION_FILEVERSION_SMC_NUM		3.3.11.0
#define VERSION_FILEVERSION_SMC_STR		"3.3.11.0"

#define VERSION_FILEVERSION_CONSENT_NUM		3.3.11.0
#define VERSION_FILEVERSION_CONSENT_STR		"3.3.11.0"

//////////////// DRAGONICA Tool Information
#define VERSION_FILEVERSION_SVRMNG_NUM		3.3.11.0
#define VERSION_FILEVERSION_SVRMNG_STR		"3.3.11.0"

