#ifndef WEAPON_LOHENGRIN_GMCOMMAND_GMCOMMAND_H
#define WEAPON_LOHENGRIN_GMCOMMAND_GMCOMMAND_H

#include "dbtables.h"

// GodCmd
typedef enum eGMCmdType : int
{
	GMCMD_NONE						= 0,
	GMCMD_GIVEITEM					= 1,
	GMCMD_GIVEITEMSET				= 2,
	GMCMD_SETITEMCOUNT				= 3,

	GMCMD_CLASSCHANGE				= 4,
	GMCMD_SKILLPOINT				= 5,
	GMCMD_GMABIL					= 6,
	GMCMD_HEALME					= 7,
	GMCMD_QUEST						= 8,
	GMCMD_GMABIL64					= 9,
	GMCMD_DROPITEM					= 10,

	GMCMD_RESET_MONEY				= 11,
	GMCMD_NOTICE_ALL				= 12,
	GMCMD_KICKUSER					= 13,
	GMCMD_BLOCKUSER					= 15,
	GMCMD_QUESTPARAM				= 16,

	GMCMD_SPEEDCHANGE				= 18,
	GMCMD_COOLTIMEINIT				= 19,
	GMCMD_KILLUNIT					= 20,
	GMCMD_ADDMONSTER				= 21,

	GMCMD_MUTECHAT					= 23,
	GMCMD_QUESTBEGIN				= 24,
	GMCMD_SETABIL					= 25,
	GMCMD_SETENCHANT				= 26,

	GMCMD_MISSIONMOVE				= 27,
	GMCMD_MISSIONSTATGE				= 28,

	GMCMD_GUILD_ADDEXP				= 29,
	GMCMD_QUEST_FAILDAILYQUEST		= 30,

	GMCMD_MISSIONSCORE				= 31,

	GMCMD_GROUNDMUTE				= 32,

	GMCMD_SET_DGATTR				= 33,
	GMCMD_ADD_BS_POINT				= 34,
	GMCMD_SET_BATTLESQUARE_STATE	= 35,

	GMCMD_ADD_EFFECT				= 41,
	GMCMD_DELETE_EFFECT				= 42,

	GMCMD_SET_REALM_QUEST			= 43,

	GMCMD_SUPERGROUNDMOVE			= 44,
	GMCMD_SUPERGROUNDFLOOR			= 45,

	GMCMD_NEW_ALRAMMISSION			= 50,
	GMCMD_CLEAR_ING_QUEST			= 51,
	GM_CMD_GUILD_BOARD_REFRESH		= 52,//길드게시판 강제 갱신

	GMCMD_UNIT_SETABIL				= 60,

	// 맵이동관련
	GMCMD_MAPMOVE					= 80,// 내가 맵이동
	GMCMD_MAPMOVE_RECALL			= 81,// 소환
	GMCMD_MAPMOVE_TARGET			= 82,// 내가 거기로 감
	GMCMD_MAPMOVE_TARGET_TOMAP		= 83,// 다른놈을 이동시킴

	GMCMD_COUPLE_INIT				= 90,

	GMCMD_TELEPORT_TO_MON			= 91,// 그라운드내에 지정한 몬스터 번호의 위치로 이동
	GMCMD_COPY_THAT					= 92,
	GMCMD_COPY_THAT_FROM_DB			= 93, // From 
	GMCMD_LIMIT_HP					= 94,

	GMCMD_INDUN_START_NOW			= 101,//강제시작
	GMCMD_INDUN_END_NOW				= 102,//강제종료

	GMCMD_INDUN_ADD_POINT			= 110,//강제로 포인트 얻기
	GMCMD_KOH_TRIGGER_POINT			= 111,//점령전 가디언 점령포인트 변경

	GMCMD_LOVEROUNDWIN				= 120,//러브러브 모드 라운드 승리.
	GMCMD_LOVEGAMEWIN				= 121,//러브러브 모드 게임 승리.

	GMCMD_COMMUNITY_EVENT_START		= 150, // 커뮤니티 이벤트 강제 시작.
	GMCMD_COMMUNITY_EVENT_END		= 151, // 커뮤니티 이벤트 강제 종료.
	GMCMD_MOVE_TO_COMMUNITYEENT_MAP = 152, // 커뮤니티 맵으로 이동.

	GMCMD_SET_ACHIEVEMENT			= 201,//업적 달성

	GMCMD_CLEAR_INV					= 202,//아이템 삭제

	GMCMD_SET_ACHIEVEMENT_TIMELIMIT	= 203,// 기간제 업적 시간 설정

	GMCMD_COMPLETE_ACHIEVEMENT		= 204,// 강제 업적 완료

	GODCMD_MTS_PVP_ROOMMODIFY		= 1001,// PvP 방정보 수정
	GODCMD_MTS_UM_ARTICLE_STATE		= 2001,// 경매 물품 상태를 강제로 변경 하기

	GMCMD_EMPORIA_OPEN				= 3001,
	GMCMD_EMPORIA_CLOSE				= 3002,
	GMCMD_EMPORIA_OWNER_CHANGE		= 3003,
	GMCMD_EMPORIA_BATTLE_START		= 3004,
	GMCMD_EMPORIA_BATTLE_TIMECHANGE = 3005,

	GMCMD_PET_BASE					= 3100,// 이번호는 사용은 하지 않는다.
	GMCMD_PET_CLASSCHANGE			= GMCMD_PET_BASE + GMCMD_CLASSCHANGE,
	GMCMD_PET_ADDABIL				= GMCMD_PET_BASE + GMCMD_GMABIL64,
	GMCMD_PET_SETABIL				= GMCMD_PET_BASE + GMCMD_SETABIL,
	// 3500번까지 예약

	GMCMD_OXQUIZ_OPEN				= 4001,// ox 퀴즈 이벤트 활성화
	GMCMD_OXQUIZ_STEP				= 4002,// ox 퀴즈 진행 단계 강제 이동

	GMCMD_SET_GENTIME				= 4010,// 아이템 생성 시간 변경
	GMCMD_SET_LIMITTIME				= 4011,// 아이템 기간 변경

	GMCMD_MYHOME_TEX_TIME			= 4020,// 마이홈 세금 납부 기간 변경
	GMCMD_MYHOME_AUCTION_TIME		= 4021,// 마이홈 경매 시간 종료

	GMCMD_LUCKYSTAR_OPEN			= 4022,//'행운의 별자리'이벤트 활성화
	GMCMD_LUCKYSTAR_STEP			= 4023,//'행운의 별자리'이벤트 진행 단계 강제 이동

	GMCMD_SERVER_TIME				= 4024,// 서버시간 출력

	GMCMD_CASHITEMGIFT_ADD			= 4025,//하루 한번 캐시아이템 선물주기 이벤트추가
	GMCMD_CASHITEMGIFT_DEL			= 4026,//하루 한번 캐시아이템 선물주기 이벤트삭제

	GMCMD_GODHAND					= 4027,// 인첸트확률 100%

	GMCMD_PLAYERPLAYTIMESTEP		= 4028,//전 유저 대상 피로도 초기화 및 피로도 테이블 리로드 기능 등
	GMCMD_SETPLAYERPLAYTIME			= 4029,//특정 유저대상 피로도 수정

	GMCMD_PVPLEAGUE_SETEVENT			= 4100,

	GMCMD_DEFENCE_POINT_COPY		= 4200,	// 전략 디펜스 포인트 복제기 누적회수 변경.

	GMCMD_JOBSKILL_ADD_EXPERTNESS	= 5001,
	GMCMD_JOBSKILL_ADD_EXHAUSTION	= 5002,
	GMCMD_JOBSKILL_RESET_EXHAUSTION	= 5003,
	GMCMD_JOBSKILL_ALWAYS_USE_SUBTOOL	= 5004,

	GMCMD_PREMIUM_SERVICE_INSERT	= 5020,//프리미엄 서비스 등록
	GMCMD_PREMIUM_SERVICE_MODIFY	= 5021,//프리미엄 서비스 수정
	GMCMD_PREMIUM_SERVICE_REMOVE	= 5022,//프리미엄 서비스 제거

	GMCMD_CART_OBJECT_MOVE_TO_PLAYER_POS = 5023,
	GMCMD_GROUND_PAUSE					= 5024,
}EGMCmdType;

class PgGMLevelChecker
{
public:
	explicit PgGMLevelChecker( CONT_DEFGMCMD const &kContDefGMCMD );
	~PgGMLevelChecker(){}

	bool IsAccess( EGMCmdType const iCmdType, BYTE const byGMLevel )const;

private:
	CONT_DEFGMCMD const &m_kContDefGMCMD;

private:
	PgGMLevelChecker();
};

#endif // WEAPON_LOHENGRIN_GMCOMMAND_GMCOMMAND_H