#ifndef WEAPON_LOHENGRIN_PACKET_PACKETTYPE5_H
#define WEAPON_LOHENGRIN_PACKET_PACKETTYPE5_H

unsigned short const PACKET_TYPE5_BASE = 50000;
unsigned short const PACKET_TYPE5_MAX = 59999;


//채팅, 메신져 (모든 패킷은 클라이언트 -> 스위치 -> 맵 -> 센터 -> 컨텐츠)
//PACKET_DEF(PT_T_T_CHAT_START,					50000 )		//일반채팅, 메신져 예약 시작
PACKET_DEF(PT_C_M_REQ_CHAT_INPUTNOW,			50001 )		//일반채팅 입력중 요청			(...) 표시
PACKET_DEF(PT_M_C_NFY_CHAT_INPUTNOW,			50002 )

PACKET_DEF(PT_C_M_REQ_CHAT,						50003 )		//일반 대화 (맵으로) (일부는 컨텐츠로)
PACKET_DEF(PT_M_C_NFY_CHAT,						50004 )
PACKET_DEF(PT_C_M_REQ_CHAT_2ND,					50005 )

//메신져, 친구목록
PACKET_DEF(PT_C_N_REQ_MSN_FRIENDCOMMAND,		50006 )		//친구(Client -> Contents)
PACKET_DEF(PT_N_C_ANS_MSN_FRIENDCOMMAND,		50007 )
PACKET_DEF(PT_N_T_REQ_MSN_FRIENDCOMMAND,		50008 )		//친구(Contents -> DB)
PACKET_DEF(PT_T_N_ANS_MSN_FRIENDCOMMAND,		50009 )

PACKET_DEF(PT_N_T_REQ_MSN_FULL_DATA,			50010 )
PACKET_DEF(PT_T_N_NFY_MSN_FULL_DATA,			50011 )
PACKET_DEF(PT_N_C_NFY_MSN_ELEMENT_MODIFY,		50012 )

PACKET_DEF(PT_C_M_REQ_CHAT_FOR_STRESS_TEST,		50013 )
PACKET_DEF(PT_C_M_REQ_ECHO_CHAT,				50014 )
PACKET_DEF(PT_C_N_REQ_MSN_FRIENDCOMMAND_2ND,	50015 )
PACKET_DEF(PT_T_N_NFY_MSN_FULL_DATA_2ND,		50016 )
PACKET_DEF(PT_C_M_REQ_CHAT_INPUTNOW_2ND,		50017 )
PACKET_DEF(PT_T_N_REQ_FRIEND_LINK_INFO,			50018 )
PACKET_DEF(PT_C_M_REQ_STATUS_CHANGE,			50019 )
PACKET_DEF(PT_M_C_ANS_STATUS_CHANGE,			50020 )

//거래
PACKET_DEF(PT_N_T_NFY_TRADE,						50021 )
PACKET_DEF(PT_M_C_NFY_TRADE,						50022 )

//길드
PACKET_DEF(PT_C_N_REQ_GUILD_COMMAND,			PACKET_TYPE5_BASE+101)
PACKET_DEF(PT_N_C_ANS_GUILD_COMMAND,			PACKET_TYPE5_BASE+102)
PACKET_DEF(PT_N_T_REQ_GUILD_COMMAND,			PACKET_TYPE5_BASE+103)
PACKET_DEF(PT_N_M_NFY_GUILD_COMMAND,			PACKET_TYPE5_BASE+105)
PACKET_DEF(PT_M_T_REQ_GUILD_COMMAND,			PACKET_TYPE5_BASE+106)
PACKET_DEF(PT_T_N_ANS_GUILD_COMMAND_RAW,		PACKET_TYPE5_BASE+107)
PACKET_DEF(PT_M_N_REQ_GUILD_COMMAND,			PACKET_TYPE5_BASE+109)
PACKET_DEF(PT_A_N_REQ_GUILD_MAIL,				PACKET_TYPE5_BASE+110)

PACKET_DEF(PT_M_N_REQ_GET_GUILD_MEMBER_GRADE,	PACKET_TYPE5_BASE+111)
PACKET_DEF(PT_N_M_ANS_GET_GUILD_MEMBER_GRADE,	PACKET_TYPE5_BASE+112)
PACKET_DEF(PT_A_N_REQ_INIT_GUILD_OWNER_LAST_LOGIN_DAY,	PACKET_TYPE5_BASE+113)
PACKET_DEF(PT_A_N_REQ_GUILD_OWNER_LAST_LOGIN_DAY,	PACKET_TYPE5_BASE+114)

PACKET_DEF(PT_A_N_REQ_GET_ENTRANCE_OPEN_GUILD,		PACKET_TYPE5_BASE+115) // 길드가입 신청을 허용한 길드 목록(컨텐츠->DB) 서버최초 기동 시, 매 24시마다.
PACKET_DEF(PT_A_N_REQ_GET_GUILD_APPLICANT_LIST,		PACKET_TYPE5_BASE+116) // 길드 신청자에 대한 목록(컨텐츠->DB) 서버 최초 기동시 딱 한번.
PACKET_DEF(PT_C_N_REQ_GET_ENTRANCE_OPEN_GUILD,		PACKET_TYPE5_BASE+117) // 길드가입 신청을 허용한 길드 목록(클라이언트->컨텐츠)
PACKET_DEF(PT_N_C_ANS_GET_ENTRANC_OPEN_GUILD,		PACKET_TYPE5_BASE+118)
PACKET_DEF(PT_C_N_REQ_GUILD_ENTRANCE,				PACKET_TYPE5_BASE+119) // 길드가입 요청(게시판)
PACKET_DEF(PT_N_C_ANS_GUILD_ENTRANCE,				PACKET_TYPE5_BASE+120)
PACKET_DEF(PT_N_C_NFY_GUILD_ENTRANCE_STATE,			PACKET_TYPE5_BASE+121) // 길드 가입 요청 상태(로그인했을 때 상태를 받아오기 위함)
PACKET_DEF(PT_N_C_NFY_NEW_GUILD_APPLICANT,			PACKET_TYPE5_BASE+122) // 새로운 길드가입요청이 들어왔다.
PACKET_DEF(PT_C_N_REQ_GUILD_ENTRANCE_CANCEL,		PACKET_TYPE5_BASE+123) // 길드가입 신청 취소 요청
PACKET_DEF(PT_N_C_NFY_GUILD_ENTRANCE_CANCEL,		PACKET_TYPE5_BASE+124) // 길드가입 신청을 취소했다.
PACKET_DEF(PT_A_N_REQ_MODIFY_GUILD_ITEM,			PACKET_TYPE5_BASE+125) // 길드금고 아이템 수정
PACKET_DEF(PT_N_C_REQ_PAYMENT_GUILD_ENTRANCE_FEE,	PACKET_TYPE5_BASE+126) // 길드가입 비용 지불
PACKET_DEF(PT_A_N_REQ_DELETE_GUILD_INVENTORY_LOG,	PACKET_TYPE5_BASE+127) // 길드로그 삭제(2주가 지난데이터)
PACKET_DEF(PT_M_N_NFY_GUILD_INVENTORY_FAIL,			PACKET_TYPE5_BASE+128) // 길드인벤토리 작업 실패 알림( 맵->컨텐츠 )

//커플
PACKET_DEF(PT_C_N_REQ_COUPLE_COMMAND,			PACKET_TYPE5_BASE+201)
PACKET_DEF(PT_N_C_ANS_COUPLE_COMMAND,			PACKET_TYPE5_BASE+202)
PACKET_DEF(PT_N_M_ANS_COUPLE_COMMAND,			PACKET_TYPE5_BASE+203)
PACKET_DEF(PT_N_T_REQ_COUPLE_COMMAND,			PACKET_TYPE5_BASE+204)
PACKET_DEF(PT_T_N_ANS_COUPLE_COMMAND,			PACKET_TYPE5_BASE+205)

//결혼
PACKET_DEF(PT_C_M_REQ_MARRY_COMMAND,			PACKET_TYPE5_BASE+301);
PACKET_DEF(PT_M_C_ANS_MARRY_COMMAND,			PACKET_TYPE5_BASE+302);
PACKET_DEF(PT_T_C_NFY_MARRY,					PACKET_TYPE5_BASE+303);
PACKET_DEF(PT_T_M_MARRY_COMMAND,				PACKET_TYPE5_BASE+304);

//공지
PACKET_DEF(PT_C_N_REQ_CHAT_NOTICE,				50401 )		//공지 월드 전체

PACKET_DEF( PT_M_N_NFY_NOTICE_PACKET,			50405 )
PACKET_DEF( PT_N_C_NFY_NOTICE_PACKET,			50406 ) // 전 유저한테 패킷을 보내라.

PACKET_DEF( PT_M_O_REQ_PLAYERTIME_DEFEND,		50408 )
PACKET_DEF( PT_M_C_REQ_PLAYERTIME_DEFEND,		50409 )

//PACKET_DEF(PT_T_T_CONTENTS_MESSAGE_START,		50500 )		//Contents Task Message 예약
PACKET_DEF(PT_A_U_SEND_TOUSER_BYCHARGUID,		50501 )	//CharGuid로 패킷을 전송
PACKET_DEF(PT_A_U_SEND_TOUSER_BYCHARGUIDS,		50502 )	//CharGuid 목록으로 패킷을 전송
PACKET_DEF(PT_A_U_SEND_TOPARTY_BYCHARGUID,		50503 ) //CharGuid로 파티 원들에게 패킷을 전송(나포함)
PACKET_DEF(PT_A_U_SEND_TOFRIEND_BYCHARGUID,	50504 ) //CharGuid로 친구들에게 패킷을 전송(나포함)
PACKET_DEF(PT_A_U_SEND_TOGUILD_BYCHARGUID,		50505 )
PACKET_DEF(PT_A_U_SEND_BROADCAST_GUILD,			50506)
PACKET_DEF(PT_N_M_NFY_MOVE_TO_SRC_GND,			50507 )	// 유저를 원래의 그라운드로 복귀시켜주라
PACKET_DEF(PT_A_U_SEND_TOMAP_BYCHARGUID,		50508 ) //유저가 위치한 맵서버로 패킷을 전송한다.
PACKET_DEF(PT_A_U_SEND_CHANGE_PLACE,			50509 )	//PvP방정보가 변경되었다.
PACKET_DEF(PT_A_U_SEND_TOFRIEND_PARTY,			50510 )	//Party Friend
PACKET_DEF(PT_A_U_SEND_TOFRIEND_PARTYINFO,		50511 )	//Party Friend



PACKET_DEF(  PT_O_C_NFY_GMCHAT,					50601 )	// GM툴에서 센터를 거쳐 클라로 전송
PACKET_DEF( PT_C_O_REQ_GMCHAT,					50602 )	// 클라에서 센터를 거쳐 GM툴로 전송
PACKET_DEF( PT_T_C_NFY_NOTICE,					50603 )	// 센터에서 맵서버에게 공지를 내린다.
PACKET_DEF( PT_T_C_NFY_BULLHORN,				50604 )	// 확성기 사용 메시지 전송

//진정 접수
PACKET_DEF( PT_C_GM_REQ_RECEIPT_PETITION,		50605)	// 클라에서 진정 접수
PACKET_DEF( PT_GM_C_ANS_RECEIPT_PETITION,		50606)	// 진정 접수 확인
PACKET_DEF( PT_C_GM_REQ_REMAINDER_PETITION,		50607)	// 남은 진정수 요청
PACKET_DEF( PT_GM_C_ANS_REMAINDER_PETITION,		50608)	// 남은 진정수 확인
PACKET_DEF( PT_GM_C_ANS_WAIT_RECEIPT,			50609)	// 니가 접수한 진정이 아직 처리되지 못했다!!

//WebGmTool에서 유저 정보 변경(실시간 커맨드 포함)
//PACKET_DEF( PT_T_M_REQ_CHANGE_STATE_INFO,		50700)	//캐릭터 정보 수정// 실시간이 사라지므로 이건 안씀.
PACKET_DEF( PT_T_M_REQ_CHANGE_CHARACTER_POS,	50701)  //캐릭터 위치 이동
//PACKET_DEF( PT_M_T_ANS_CHANGE_CHARACTER_POS,	50702)  //캐릭터 위치 이동 확인(PT_M_T_REQ_MAP_MOVE 사용)
PACKET_DEF( PT_T_I_REQ_CREATE_ITEM,				50703)	//아이템 생성(이넘은 우편으로 가니 확인 패킷은 없어도 된다)
PACKET_DEF( PT_T_I_REQ_MODIFY_ITEM,				50704)	//아이템 수정 
PACKET_DEF( PT_M_T_ANS_MODIFY_ITEM,				50705)	//아이템 수정 확인
PACKET_DEF( PT_T_M_REQ_DELETE_ITEM,				50706)	//아이템 삭제
PACKET_DEF( PT_M_T_ANS_DELETE_ITEM,				50707)	//아이템 삭제 확인
PACKET_DEF( PT_T_M_REQ_CHANGE_SKILL_INFO,		50708)	//스킬 정보 수정
PACKET_DEF( PT_M_T_ANS_CHANGE_SKILL_INFO,		50709)	//스킬 정보 수정 확인
PACKET_DEF( PT_T_M_REQ_CHANGE_QUEST_INFO,		50710)	//퀘스트 정보 수정
PACKET_DEF( PT_M_T_ANS_CHANGE_QUEST_INFO,		50711)	//퀘스트 정보 수정 확인
PACKET_DEF( PT_T_M_REQ_CHANGE_GM_LEVEL,			50712)	//GM Level변경	Center->Map으로 수정요청
PACKET_DEF( PT_M_T_ANS_CHANGE_GM_LEVEL,			50713)	//GM Level변경	Map->Center로 DB에 저장 요청
PACKET_DEF( PT_T_M_REQ_CHARACTER_BASEINFO,		50714)	//캐릭터 기본 정보
PACKET_DEF( PT_M_T_ANS_CHARACTER_BASEINFO,      50715)
PACKET_DEF( PT_T_M_REQ_USER_MUTE,				50716)	//채금
PACKET_DEF( PT_N_T_REQ_KICK_USER,				50717)	//WebGmTool로 캐릭터 정보 수정시 사용
PACKET_DEF( PT_T_N_ANS_KICK_USER,				50718)	//WebGmTool로 캐릭터 정보 수정시 사용

PACKET_DEF( PT_T_M_NFY_MONSTERGEN,				50719)	//이벤트에서 몬스터 소환시 사용
PACKET_DEF( PT_A_A_NFY_REALM_STATE,				50720)	// Realm State changed (Contents -> Immigration -> Login)
PACKET_DEF( PT_M_G_NFY_EVENT_ABIL,				50721)	//이벤트에서 그라운드에 이벤트 어빌을 셋팅시에 사용

PACKET_DEF( PT_C_M_REQ_GET_DAILY,               50722)  // Notify player about daily reward
PACKET_DEF( PT_M_C_NFY_GET_DAILY,               50723)  // Notify player about daily reward

PACKET_DEF( PT_M_C_NFY_BATTLE_PASS_INFO,        50724)
PACKET_DEF( PT_C_M_REQ_BATTLE_PASS_QUEST,       50725)
PACKET_DEF( PT_M_C_NFY_BATTLE_PASS_QUEST,       50726)
PACKET_DEF( PT_A_N_REQ_BATTLE_PASS_INFO,        50727)
PACKET_DEF( PT_N_A_NFY_BATTLE_PASS_INFO,        50728)

#endif // WEAPON_LOHENGRIN_PACKET_PACKETTYPE5_H