#ifndef WEAPON_LOHENGRIN_PACKET_PACKETTYPE3_H
#define WEAPON_LOHENGRIN_PACKET_PACKETTYPE3_H

PACKET_ID_TYPE const PACKET_TYPE3_BASE = 30000;
PACKET_ID_TYPE const PACKET_TYPE3_MAX = 39999;

//+-------------------------------------------------------------------------------------------------+
//| # Observer Mode																|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const OBMODE_PACKET_BASE = PACKET_TYPE3_BASE;

PACKET_DEF( PT_M_C_NFY_OBMODE_START,				OBMODE_PACKET_BASE)

PACKET_DEF( PT_C_M_REQ_OBMODE_END,					OBMODE_PACKET_BASE+1)
PACKET_DEF( PT_M_C_NFY_OBMODE_END,					OBMODE_PACKET_BASE+2)

PACKET_DEF( PT_C_M_REQ_OBMODE_TARGET_CHANGE,		OBMODE_PACKET_BASE+3)
PACKET_DEF( PT_M_C_NFY_OBMODE_TARGET_CHANGE,		OBMODE_PACKET_BASE+4)
PACKET_DEF( PT_M_C_ANS_OBMODE_TARGET_FAILED,		OBMODE_PACKET_BASE+5)

PACKET_DEF( PT_IM_A_NFY_ANTIHACK_CONTROL,			OBMODE_PACKET_BASE+6)

//+-------------------------------------------------------------------------------------------------+
//| # Event 시작을 알리는 Packet																	|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const EVENT_PACKET_BASE = PACKET_TYPE3_BASE + 100;

PACKET_DEF( PT_N_C_NFY_BOSS_RESULT,					EVENT_PACKET_BASE)

PACKET_DEF( PT_M_N_NFY_JOIN_INDUN_PLAYER,			EVENT_PACKET_BASE+3)
PACKET_DEF( PT_M_N_NFY_LEAVE_INDUN_PLAYER,			EVENT_PACKET_BASE+4)
PACKET_DEF( PT_M_N_NFY_RESULT_INDUN,				EVENT_PACKET_BASE+5)
PACKET_DEF( PT_M_N_NFY_RESULTITEM_INDUN,			EVENT_PACKET_BASE+6)
PACKET_DEF( PT_C_M_REQ_RESULT_END,					EVENT_PACKET_BASE+7)

//+-------------------------------------------------------------------------------------------------+
//| # 원정대 결과창 관련 Packet																		|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const EXPEDITION_COMPLETE_PACKET_BASE = PACKET_TYPE3_BASE + 300;

PACKET_DEF( PT_N_C_NFY_EXPEDITION_BOSS_RESULT,		EXPEDITION_COMPLETE_PACKET_BASE)

PACKET_DEF( PT_M_N_NFY_EXPEDITION_JOIN_PLAYER,		EXPEDITION_COMPLETE_PACKET_BASE+3)
PACKET_DEF( PT_M_N_NFY_EXPEDITION_LEAVE_PLAYER,		EXPEDITION_COMPLETE_PACKET_BASE+4)
PACKET_DEF( PT_M_N_NFY_EXPEDITION_RESULT,			EXPEDITION_COMPLETE_PACKET_BASE+5)
PACKET_DEF( PT_M_N_NFY_EXPEDITION_RESULTITEM,		EXPEDITION_COMPLETE_PACKET_BASE+6)
PACKET_DEF( PT_C_M_REQ_EXPEDITION_RESULT_END,		EXPEDITION_COMPLETE_PACKET_BASE+7)
PACKET_DEF( PT_N_C_NFY_START_TENDER,				EXPEDITION_COMPLETE_PACKET_BASE+8)	// 입찰 시작
PACKET_DEF( PT_N_C_NFY_ACCEPTANCE_USER,				EXPEDITION_COMPLETE_PACKET_BASE+9)	// 낙찰 알림
PACKET_DEF( PT_C_N_REQ_TENDER_ITEM,					EXPEDITION_COMPLETE_PACKET_BASE+10)	// 아이템 입찰 요청
PACKET_DEF( PT_C_N_REQ_GIVEUP_TENDER,				EXPEDITION_COMPLETE_PACKET_BASE+11) // 아이템 입찰 취소 요청
PACKET_DEF( PT_M_C_NFY_EXPEDITION_RESULT_END,		EXPEDITION_COMPLETE_PACKET_BASE+12) // 결산 모두 종료
PACKET_DEF( PT_N_M_NFY_EXPEDITION_RESULT_END,		EXPEDITION_COMPLETE_PACKET_BASE+13) // 결산 종료 맵으로 알림.
PACKET_DEF( PT_M_N_NFY_EXPEDITION_INDUN_CLOSE,		EXPEDITION_COMPLETE_PACKET_BASE+14) // 원정대 던전 끝.

//+-------------------------------------------------------------------------------------------------+
//| # Ranking System																				|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const RANKING_PACKET_BASE = PACKET_TYPE3_BASE + 490;

//+-------------------------------------------------------------------------------------------------+
//| # 전쟁관련 Packet																				|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const WAR_PACKET_BASE = PACKET_TYPE3_BASE + 500;

PACKET_DEF( PT_M_C_NFY_GAME_INTRUDER,				WAR_PACKET_BASE+1)//난입
PACKET_DEF( PT_M_C_NFY_GAME_EXIT,					WAR_PACKET_BASE+2)//나갔네?
PACKET_DEF( PT_M_C_NFY_GAME_WAIT,					WAR_PACKET_BASE+3)
PACKET_DEF( PT_M_C_NFY_GAME_READY,					WAR_PACKET_BASE+4)
PACKET_DEF( PT_M_C_NFY_GAME_START,					WAR_PACKET_BASE+5)
PACKET_DEF( PT_M_C_NFY_GAME_END,					WAR_PACKET_BASE+6)
PACKET_DEF( PT_M_C_NFY_GAME_RESULT_END,				WAR_PACKET_BASE+7)
PACKET_DEF( PT_M_C_NFY_SYNC_GAMTTIME,				WAR_PACKET_BASE+8)

PACKET_DEF( PT_T_M_NFY_CANCEL_GROUND,				WAR_PACKET_BASE+10 )
PACKET_DEF( PT_T_M_REQ_READY_GROUND,				WAR_PACKET_BASE+11 )
PACKET_DEF( PT_M_T_ANS_READY_GROUND,				WAR_PACKET_BASE+12 )
PACKET_DEF( PT_M_T_NFY_GAME_RESULT,					WAR_PACKET_BASE+13 )	// 게임결과
PACKET_DEF( PT_M_C_NFY_GAME_RESULT,					WAR_PACKET_BASE+14 )	// PvP 결과.
PACKET_DEF( PT_M_T_NFY_GAME_RESULT_END,				WAR_PACKET_BASE+15 )	// 게임결과 끝.

PACKET_DEF( PT_M_C_NFY_GAME_EVENT_KILL,				WAR_PACKET_BASE+70)
PACKET_DEF( PT_M_C_NFY_ABIL_DEC,					WAR_PACKET_BASE+71)
PACKET_DEF( PT_M_C_NFY_ADD_POINT_USER,				WAR_PACKET_BASE+72)
PACKET_DEF( PT_M_C_NFY_OBJEVER_USER,				WAR_PACKET_BASE+73)		// 현재 사용하지 않는 패킷(11/12/14)
PACKET_DEF( PT_M_C_NFY_GAME_EVENT_CHANGEPOINT,		WAR_PACKET_BASE+74)

PACKET_DEF( PT_C_M_REQ_SELECT_BATTLE_AREA,			WAR_PACKET_BASE+80 )
PACKET_DEF( PT_M_C_NFY_BATTLE_AREA_USER,			WAR_PACKET_BASE+81 )

PACKET_DEF( PT_C_M_REQ_DUEL_PVP,					WAR_PACKET_BASE+100)	// PvP 신청
PACKET_DEF( PT_C_M_NFY_DUEL_PVP_CANCEL,				WAR_PACKET_BASE+101)	// PvP 신청 취소
PACKET_DEF( PT_M_C_REQ_DUEL_PVP,					WAR_PACKET_BASE+102)
PACKET_DEF( PT_C_M_ANS_DUEL_PVP,					WAR_PACKET_BASE+103)
PACKET_DEF( PT_M_C_ANS_DUEL_PVP,					WAR_PACKET_BASE+104)
PACKET_DEF( PT_C_M_ERROR_DUEL_PVP,					WAR_PACKET_BASE+105)
PACKET_DEF( PT_M_C_ERROR_DUEL_PVP,					WAR_PACKET_BASE+106)
PACKET_DEF( PT_M_C_ERROR_INPARTY_PVP,				WAR_PACKET_BASE+109)
PACKET_DEF( PT_M_C_NFY_DUEL_START_COUNT,			WAR_PACKET_BASE+110)
PACKET_DEF( PT_M_C_NFY_DUEL_END_COUNT,				WAR_PACKET_BASE+111)
PACKET_DEF( PT_M_C_NFY_DUEL_OUT_COUNT,				WAR_PACKET_BASE+112)
PACKET_DEF( PT_M_C_NFY_DUEL_BEGIN,					WAR_PACKET_BASE+113)
PACKET_DEF( PT_M_C_NFY_DUEL_FINISH,					WAR_PACKET_BASE+114)
PACKET_DEF( PT_M_C_NFY_DUEL_CANCEL_END_COUNT,		WAR_PACKET_BASE+115)
PACKET_DEF( PT_M_C_NFY_DUEL_CANCEL_OUT_COUNT,		WAR_PACKET_BASE+116)

PACKET_DEF( PT_A_G_NFY_DESTROY_OBJECT_REGEN,		WAR_PACKET_BASE+120)	// 유물파괴전 오브젝트를 리젠 시켜주어라
PACKET_DEF( PT_A_G_NFY_PVP_REWARD,					WAR_PACKET_BASE+121)
PACKET_DEF( PT_A_G_NFY_RESPAWN,						WAR_PACKET_BASE+122)
PACKET_DEF( PT_A_G_NFY_ADD_STATETIME,				WAR_PACKET_BASE+123)	// 

PACKET_DEF( PT_N_M_REQ_READY_EMPORIA_BATTLE,		WAR_PACKET_BASE+135 )

PACKET_DEF( PT_M_N_NFY_GAME_READY,					WAR_PACKET_BASE+136 )

PACKET_DEF( PT_M_C_NFY_SELECT_ENTRY,					WAR_PACKET_BASE+137 )//에이스 매치 엔트리 선택해라
PACKET_DEF( PT_C_M_ANS_SELECT_ENTRY,					WAR_PACKET_BASE+138 )//엔트리 선택한것 응답

//+-------------------------------------------------------------------------------------------------+
//| # PvP Lobby Packet																				|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const LOBBY_PACKET_BASE = PACKET_TYPE3_BASE + 700;

PACKET_DEF( PT_C_M_REQ_JOIN_LOBBY,					LOBBY_PACKET_BASE	)
PACKET_DEF( PT_T_T_REQ_JOIN_LOBBY,					LOBBY_PACKET_BASE+1	)
PACKET_DEF( PT_T_C_ANS_JOIN_LOBBY,					LOBBY_PACKET_BASE+2	)
PACKET_DEF( PT_C_T_REQ_EXIT_LOBBY,					LOBBY_PACKET_BASE+3 )
PACKET_DEF( PT_T_T_REQ_EXIT_LOBBY,					LOBBY_PACKET_BASE+4 )

PACKET_DEF( PT_T_C_NFY_ROOMLIST_REMOVE,				LOBBY_PACKET_BASE+5 )
PACKET_DEF( PT_T_C_NFY_ROOMLIST_UPDATE,				LOBBY_PACKET_BASE+6 )

PACKET_DEF( PT_C_T_REQ_CREATE_ROOM,					LOBBY_PACKET_BASE+7 )// 방을 만들어 줘.
PACKET_DEF( PT_T_C_ANS_CREATE_ROOM,					LOBBY_PACKET_BASE+8 )

PACKET_DEF( PT_C_T_REQ_JOIN_ROOM,					LOBBY_PACKET_BASE+9 )// 방에 들어가겠다.
PACKET_DEF( PT_T_C_ANS_JOIN_ROOM,					LOBBY_PACKET_BASE+10 )
PACKET_DEF( PT_C_T_REQ_EXIT_ROOM,					LOBBY_PACKET_BASE+11 )//방에서 나가겠다.
PACKET_DEF( PT_T_C_NFY_EXIT_ROOM_USER,				LOBBY_PACKET_BASE+12 )
PACKET_DEF( PT_T_C_NFY_RELOAD_ROOM,					LOBBY_PACKET_BASE+13 )

PACKET_DEF( PT_C_T_REQ_TEAM_CHANGE,					LOBBY_PACKET_BASE+14 )//팀을 변경 하겠다.
PACKET_DEF( PT_T_C_ANS_TEAM_CHANGE,					LOBBY_PACKET_BASE+15 )
PACKET_DEF( PT_T_C_NFY_USER_STATUS_CHANGE,			LOBBY_PACKET_BASE+16 )

PACKET_DEF( PT_C_T_REQ_GAME_READY,					LOBBY_PACKET_BASE+17 )// PvP Game을 시작하자.
PACKET_DEF( PT_T_M_NFY_EXIT_ROOM,					LOBBY_PACKET_BASE+18 )

PACKET_DEF( PT_C_T_REQ_MODIFY_ROOM,					LOBBY_PACKET_BASE+19 )
PACKET_DEF( PT_T_C_ANS_MODIFY_ROOM,					LOBBY_PACKET_BASE+20 )
PACKET_DEF( PT_C_T_REQ_KICK_ROOM_USER,				LOBBY_PACKET_BASE+21 )
PACKET_DEF( PT_C_T_REQ_CHANGE_LOBBY,				LOBBY_PACKET_BASE+22 )
PACKET_DEF( PT_T_T_REQ_CHANGE_LOBBY,				LOBBY_PACKET_BASE+23 )

PACKET_DEF( PT_C_T_REQ_SLOTSTATUS_CHANGE,			LOBBY_PACKET_BASE+24 )
PACKET_DEF( PT_T_C_ANS_SLOTSTATUS_CHANGE,			LOBBY_PACKET_BASE+25 )

PACKET_DEF( PT_C_T_REQ_ENTRY_CHANGE,			LOBBY_PACKET_BASE+26 )
PACKET_DEF( PT_T_C_ANS_ENTRY_CHANGE,			LOBBY_PACKET_BASE+27 )

PACKET_DEF( PT_C_T_REQ_ENTRUST_MASTER,				LOBBY_PACKET_BASE+28 )
PACKET_DEF( PT_T_C_ANS_ENTRUST_MASTER,				LOBBY_PACKET_BASE+29 )
PACKET_DEF( PT_C_T_REQ_WITH_PVP,					LOBBY_PACKET_BASE+30 )
PACKET_DEF( PT_T_C_ANS_WITH_PVP,					LOBBY_PACKET_BASE+31 )
PACKET_DEF( PT_C_T_REQ_INVITE_PVP,					LOBBY_PACKET_BASE+32 )
PACKET_DEF( PT_T_C_ANS_INVITE_PVP,					LOBBY_PACKET_BASE+33 )

PACKET_DEF( PT_T_T_REQ_KICK_ROOM_USER,				LOBBY_PACKET_BASE+34 )
PACKET_DEF( PT_T_M_REQ_KICK_ROOM_USER,				LOBBY_PACKET_BASE+35 )
PACKET_DEF( PT_M_T_ANS_KICK_ROOM_USER_NOTFOUND,		LOBBY_PACKET_BASE+36 )

PACKET_DEF( PT_C_T_REQ_GET_PVPRANKING,				LOBBY_PACKET_BASE+37 )
PACKET_DEF( PT_T_C_ANS_GET_PVPRANKING,				LOBBY_PACKET_BASE+38 )
PACKET_DEF( PT_T_C_NFY_PVPRANK,						LOBBY_PACKET_BASE+39 )

PACKET_DEF( PT_A_TO_ROOM,							LOBBY_PACKET_BASE+40 )
PACKET_DEF( PT_ROOM_TO_LOBBY_USER,					LOBBY_PACKET_BASE+41 )// Room에서 나가서 Lobby로 돌아간다.
PACKET_DEF( PT_ROOM_TO_LOBBY_REMOVED,				LOBBY_PACKET_BASE+42 )
PACKET_DEF( PT_ROOM_TO_LOBBY_MODIFYED,				LOBBY_PACKET_BASE+43 )

PACKET_DEF( PT_LOBBY_TO_CELL_JOIN,					LOBBY_PACKET_BASE+44 )
PACKET_DEF( PT_LOBBY_TO_CELL_BROADCAST,				LOBBY_PACKET_BASE+45 )

PACKET_DEF( PT_T_C_NFY_PVPLOBBY_LIST_EVENT,			LOBBY_PACKET_BASE+46 )

PACKET_DEF( PT_T_N_REQ_GET_PVPLOBBY_INFO,			LOBBY_PACKET_BASE+47 )
PACKET_DEF( PT_N_T_ANS_GET_PVPLOBBY_INFO,			LOBBY_PACKET_BASE+48 )

PACKET_DEF( PT_C_M_REQ_PVP_SELECTOR,				LOBBY_PACKET_BASE+50 )
PACKET_DEF( PT_M_C_ANS_PVP_SELECTOR,				LOBBY_PACKET_BASE+51 )
PACKET_DEF( PT_C_M_REQ_PVP_SELECTOR_CANCEL,			LOBBY_PACKET_BASE+52 )

PACKET_DEF( PT_C_T_REQ_INVATE_FAIL,					LOBBY_PACKET_BASE+53 )
PACKET_DEF( PT_T_C_ANS_INVATE_FAIL,					LOBBY_PACKET_BASE+54 )

//+-------------------------------------------------------------------------------------------------+
//| # Emporia Packet																				|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const EMPORIA_PACKET_BASE = PACKET_TYPE3_BASE + 800;

PACKET_DEF( PT_A_N_REQ_EMPORIA_GM_COMMAND,			EMPORIA_PACKET_BASE+0 )//엠포리아에 대한 GM명령

// Client간 패킷(lua에서 호출 하는 것도 있을 수 있다.
PACKET_DEF( PT_C_N_REQ_EMPORIA_STATUS_LIST,			EMPORIA_PACKET_BASE+1 )//엠포리아 현황 리스트를 줘봐라.
PACKET_DEF( PT_N_C_ANS_EMPORIA_STATUS_LIST,			EMPORIA_PACKET_BASE+2 )//엠포리아 현황 리스트 여기 있다.
PACKET_DEF( PT_N_C_ANS_EMPORIA_BATTLE_RESERVE,		EMPORIA_PACKET_BASE+3 )//엠포리아 쟁탈전 신청에 대한 응답

PACKET_DEF( PT_C_M_REQ_EMPORIA_ADMINISTRATION,		EMPORIA_PACKET_BASE+4 )//
PACKET_DEF( PT_M_N_REQ_EMPORIA_ADMINISTRATION,		EMPORIA_PACKET_BASE+5 )
PACKET_DEF( PT_N_C_ANS_EMPORIA_ADMINISTRATION,		EMPORIA_PACKET_BASE+6 )

PACKET_DEF( PT_M_C_NFY_EMPORIA_FUNCTION,			EMPORIA_PACKET_BASE+8 )
PACKET_DEF( PT_M_C_NFY_EMPORIA_FUNCTION_REMOVE,		EMPORIA_PACKET_BASE+9 )

PACKET_DEF( PT_C_M_REQ_USE_EMPORIA_FUNCTION,		EMPORIA_PACKET_BASE+10 )
PACKET_DEF( PT_M_C_ANS_USE_EMPORIA_FUNCTION,		EMPORIA_PACKET_BASE+11 )
PACKET_DEF( PT_C_M_REQ_JOIN_EMPORIA,				EMPORIA_PACKET_BASE+12 )

PACKET_DEF( PT_C_M_REQ_GET_EMPORIA_ADMINISTRATOR,	EMPORIA_PACKET_BASE+13 )
PACKET_DEF( PT_M_N_REQ_GET_EMPORIA_ADMINISTRATOR,	EMPORIA_PACKET_BASE+14 )
PACKET_DEF( PT_N_C_ANS_GET_EMPORIA_ADMINISTRATOR,	EMPORIA_PACKET_BASE+15 )

PACKET_DEF( PT_M_C_NFY_BATTLE_CHANGE_AREA_TO_BIGDRAGON, EMPORIA_PACKET_BASE+16 )

PACKET_DEF( PT_C_M_REG_JOIN_EMPORIA_MERCENARY,		EMPORIA_PACKET_BASE+17 )// 용병으로 참가


// Server간 패킷
PACKET_DEF( PT_N_N_NFY_GUILD_REMOVE,					EMPORIA_PACKET_BASE+20 )// 길드가 삭제 되었다.
PACKET_DEF( PT_N_N_NFY_EMPORIA_INFO,					EMPORIA_PACKET_BASE+21 )// GuildMgr한테 통보하는 길드엠포리아 정보
PACKET_DEF( PT_N_M_NFY_EMPORIA_INFO,					EMPORIA_PACKET_BASE+22 )// 그라운드한테 통보하는 엠포리아 정보.
PACKET_DEF( PT_N_N_REQ_EMPORIA_BATTLE_RESERVE,			EMPORIA_PACKET_BASE+23 )// 엠포리아 배틀 신청(GuildMgr로 부터 받는다.)
PACKET_DEF( PT_N_N_ANS_EMPORIA_BATTLE_RESERVE,			EMPORIA_PACKET_BASE+24 )// 엠포리아 배틀 신청 결과
PACKET_DEF( PT_N_N_NFY_EMPORIA_BATTLE_RESERVE_CANCLE,	EMPORIA_PACKET_BASE+25 )// 엠포리아 배틀 신청 취소되었다.
PACKET_DEF( PT_N_N_NFY_EMPORIA_BATTLE_RESERVE_DELETE,	EMPORIA_PACKET_BASE+26 )// 엠포리아 배틀 정보 지움
PACKET_DEF( PT_N_M_REQ_EMPORIA_BATTLE_GROUND_CREATE,	EMPORIA_PACKET_BASE+27 )// 엠포리아 쟁탈전을 시작할 준비를 해라.
PACKET_DEF( PT_M_N_ANS_EMPORIA_BATTLE_GROUND_CREATE,	EMPORIA_PACKET_BASE+28 )
PACKET_DEF( PT_M_N_NFY_EMPORIA_BATTLE_RESULT,			EMPORIA_PACKET_BASE+29 )// 엠포리아 쟁탈전 결과
PACKET_DEF( PT_M_N_NFY_EMPORIA_BATTLE_USERCOUNT_FULL,	EMPORIA_PACKET_BASE+30 )// 더이상 유저를 못들어 오게 하라.

PACKET_DEF( PT_N_M_NFY_EMPORIA_PORTAL_INFO,				EMPORIA_PACKET_BASE+31 )//엠포리아 포탈정보 업데이트
PACKET_DEF( PT_M_N_REQ_EMPORIA_PORTAL_INFO,				EMPORIA_PACKET_BASE+32 )//엠포리아 포탈정보 달라...
PACKET_DEF( PT_M_C_NFY_EMPORIA_PORTAL_INFO,				EMPORIA_PACKET_BASE+33 )

PACKET_DEF( PT_N_N_NFY_REFUND_GUILD_EXP,				EMPORIA_PACKET_BASE+34 )
PACKET_DEF( PT_N_M_NFY_EMPORIA_FUNCTION_REMOVE,			EMPORIA_PACKET_BASE+35 )

PACKET_DEF( PT_N_N_REQ_GET_SETTING_MERCENARY,			EMPORIA_PACKET_BASE+36 )
PACKET_DEF( PT_N_N_ANS_GET_SETTING_MERCENARY,			EMPORIA_PACKET_BASE+37 )
PACKET_DEF( PT_N_N_NFY_GUILD_EXP_BROADCAST,				EMPORIA_PACKET_BASE+38 )

//+-------------------------------------------------------------------------------------------------+
//| # LevelUp Packet																				|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const LEVELUP_PACKET_BASE = PACKET_TYPE3_BASE + 900;

PACKET_DEF( PT_M_T_REFRESH_LEVELUP,					LEVELUP_PACKET_BASE+0 )//레벨업 정보 센터로 갱신
PACKET_DEF( PT_M_T_REFRESH_CLASS_CHANGE,			LEVELUP_PACKET_BASE+1 )//직업 변경 정보 센터로 갱신(전직 등등)

//+-------------------------------------------------------------------------------------------------+
//| # HardCoreDungeon Packet																		|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const HARDCORE_PACKET_BASE = PACKET_TYPE3_BASE + 1000;

PACKET_DEF( PT_N_T_REQ_HARDCORE_SYNC,					HARDCORE_PACKET_BASE )

PACKET_DEF( PT_M_T_REQ_REGIST_HARDCORE_VOTE,			HARDCORE_PACKET_BASE + 1 )
PACKET_DEF( PT_T_M_ANS_REGIST_HARDCORE_VOTE,			HARDCORE_PACKET_BASE + 2 )
PACKET_DEF( PT_M_C_ANS_REGIST_HARDCORE_VOTE,			HARDCORE_PACKET_BASE + 3 )
PACKET_DEF( PT_C_M_REQ_RET_HARDCORE_VOTE,				HARDCORE_PACKET_BASE + 4 )
PACKET_DEF( PT_M_T_REQ_RET_HARDCORE_VOTE,				HARDCORE_PACKET_BASE + 5 )
PACKET_DEF( PT_T_M_ANS_RET_HARDCORE_VOTE_CANCEL,		HARDCORE_PACKET_BASE + 6 )
PACKET_DEF( PT_M_C_ANS_RET_HARDCORE_VOTE_CANCEL,		HARDCORE_PACKET_BASE + 7 )

PACKET_DEF( PT_T_M_REQ_JOIN_HARDCORE,					HARDCORE_PACKET_BASE + 8 )
PACKET_DEF( PT_M_T_ANS_JOIN_HARDCORE_FAILED,			HARDCORE_PACKET_BASE + 9 )

PACKET_DEF( PT_T_T_REQ_READY_JOIN_HARDCORE,				HARDCORE_PACKET_BASE + 10 )

PACKET_DEF( PT_M_M_REQ_READY_HARDCORE_BOSS,				HARDCORE_PACKET_BASE + 11 )
PACKET_DEF( PT_M_M_ANS_READY_HARDCORE_BOSS,				HARDCORE_PACKET_BASE + 12 )
PACKET_DEF( PT_M_M_NFY_HARDCORE_BOSS_ENDTIME,			HARDCORE_PACKET_BASE + 13 )
PACKET_DEF( PT_M_C_NFY_HARDCORE_BOSS_ENDTIME,			HARDCORE_PACKET_BASE + 14 )
PACKET_DEF( PT_M_C_NFY_HARDCORE_BOSS_ENDTIME_IN,		HARDCORE_PACKET_BASE + 15 )

//+-------------------------------------------------------------------------------------------------+
//| # AlramMission Packet																			|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const ALRAMMISSION_PACKET_BASE = PACKET_TYPE3_BASE + 2000;
PACKET_DEF( PT_M_C_NFY_ALRAMMISSION_BEGIN,				ALRAMMISSION_PACKET_BASE )
PACKET_DEF( PT_M_C_NFY_ALRAMMISSION_END,				ALRAMMISSION_PACKET_BASE + 1)
PACKET_DEF( PT_M_C_NFY_ALRAMMISSION_PARAM,				ALRAMMISSION_PACKET_BASE + 2)
PACKET_DEF( PT_M_C_NFY_ALRAMMISSION_SUCCESS,			ALRAMMISSION_PACKET_BASE + 3)

//+-------------------------------------------------------------------------------------------------+
//| # PvPLeague Packet																				|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const PVPLEAGUE_PACKET_BASE = PACKET_TYPE3_BASE + 3000;
PACKET_DEF( PT_A_N_REQ_LOAD_PVPLEAGUE,				PVPLEAGUE_PACKET_BASE )
PACKET_DEF( PT_N_N_NFY_RELOAD_PVPLEAGUE,				PVPLEAGUE_PACKET_BASE + 1 )
PACKET_DEF( PT_N_N_NFY_RELOAD_PVPLEAGUE_SUB,		PVPLEAGUE_PACKET_BASE + 2 )
PACKET_DEF( PT_N_N_NFY_INIT_PVPLEAGUE,					PVPLEAGUE_PACKET_BASE + 3 )
PACKET_DEF( PT_N_N_NFY_UPDATE_PVPLEAGUE,					PVPLEAGUE_PACKET_BASE + 4 )
PACKET_DEF( PT_N_T_REQ_CREATE_PVPLEAGUE_ROOM,				PVPLEAGUE_PACKET_BASE + 5 )
PACKET_DEF( PT_T_N_ANS_CREATE_PVPLEAGUE_ROOM,				PVPLEAGUE_PACKET_BASE + 6 )

PACKET_DEF( PT_N_T_REQ_START_PVPLEAGUE_GAME,				PVPLEAGUE_PACKET_BASE + 7 )
PACKET_DEF( PT_T_N_ANS_START_PVPLEAGUE_GAME,				PVPLEAGUE_PACKET_BASE + 8 )

PACKET_DEF( PT_N_T_REQ_END_PVPLEAGUE_GAME,				PVPLEAGUE_PACKET_BASE + 9 )
PACKET_DEF( PT_T_N_ANS_END_PVPLEAGUE_GAME,				PVPLEAGUE_PACKET_BASE + 10 )

PACKET_DEF( PT_N_T_REQ_RESULT_PVPLEAGUE_GAME,				PVPLEAGUE_PACKET_BASE + 11 )
PACKET_DEF( PT_T_N_NFY_RESULT_PVPLEAGUE_GAME,				PVPLEAGUE_PACKET_BASE + 12 )
PACKET_DEF( PT_N_N_NFY_RESULT_PVPLEAGUE_GAME,				PVPLEAGUE_PACKET_BASE + 13 )

PACKET_DEF( PT_N_C_NFY_READY_PVPLEAGUE_GAME,				PVPLEAGUE_PACKET_BASE + 14 )

PACKET_DEF( PT_N_C_NFY_CLOSE_PVPLEAGUE_GAME,				PVPLEAGUE_PACKET_BASE + 15 )

PACKET_DEF( PT_C_N_REQ_REGIST_PVPLEAGUE_TEAM,				PVPLEAGUE_PACKET_BASE + 16 )
PACKET_DEF( PT_N_N_NFY_REGIST_PVPLEAGUE_TEAM,				PVPLEAGUE_PACKET_BASE + 17 )
PACKET_DEF( PT_N_C_ANS_REGIST_PVPLEAGUE_TEAM,				PVPLEAGUE_PACKET_BASE + 18 )

PACKET_DEF( PT_C_N_REQ_GIVEUP_PVPLEAGUE_TEAM,				PVPLEAGUE_PACKET_BASE + 19 )
PACKET_DEF( PT_N_N_NFY_GIVEUP_PVPLEAGUE_TEAM,				PVPLEAGUE_PACKET_BASE + 20 )
PACKET_DEF( PT_N_C_ANS_GIVEUP_PVPLEAGUE_TEAM,				PVPLEAGUE_PACKET_BASE + 21 )

PACKET_DEF( PT_N_C_NFY_PVPLEAGUE_NOTICE_MSG,				PVPLEAGUE_PACKET_BASE + 22 )

PACKET_DEF( PT_N_N_NFY_PVPLEAGUE_TEAMLEVEL,				PVPLEAGUE_PACKET_BASE + 23 )

PACKET_DEF( PT_M_C_NFY_PVP_HIDEUNIT,				PVPLEAGUE_PACKET_BASE + 24 )

PACKET_DEF( PT_C_N_REQ_QUERY_PVPLEAGUE_TEAM,				PVPLEAGUE_PACKET_BASE + 25 )
PACKET_DEF( PT_N_C_ANS_QUERY_PVPLEAGUE_TEAM,				PVPLEAGUE_PACKET_BASE + 26 )

//GM Command
PACKET_DEF( PT_A_N_REQ_PVPLEAGUE_GM_COMMAND,			PVPLEAGUE_PACKET_BASE + 27 )
PACKET_DEF( PT_C_N_REQ_PVPLEAGUE_NEXT_STATE,					PVPLEAGUE_PACKET_BASE + 28 )

//+-------------------------------------------------------------------------------------------------+
//| # PvPLeague Lobby Packet																				|
//+-------------------------------------------------------------------------------------------------+
PACKET_ID_TYPE const LEAGUE_LOBBY_PACKET_BASE = PACKET_TYPE3_BASE + 4000;

PACKET_DEF( PT_T_C_ANS_JOIN_LEAGUE_LOBBY,					LEAGUE_LOBBY_PACKET_BASE	)

PACKET_DEF( PT_C_T_REQ_JOIN_LEAGUE_ROOM,					LEAGUE_LOBBY_PACKET_BASE+1 )// 방에 들어가겠다.

PACKET_DEF( PT_T_C_NFY_REFRESH_LEAGUE_LOBBY,				LEAGUE_LOBBY_PACKET_BASE+2 )

PACKET_DEF( PT_T_N_REQ_CHANGE_STATE_LEAGUE_LOBBY,				LEAGUE_LOBBY_PACKET_BASE+3 )
PACKET_DEF( PT_N_T_NFY_CHANGE_STATE_LEAGUE_LOBBY,				LEAGUE_LOBBY_PACKET_BASE+4 )
PACKET_DEF( PT_T_C_RELOAD_LEAGUE_LOBBY,				LEAGUE_LOBBY_PACKET_BASE+5 )

#endif // WEAPON_LOHENGRIN_PACKET_PACKETTYPE3_H