#ifndef WEAPON_LOHENGRIN_PACKET_PACKETTYPE4_H
#define WEAPON_LOHENGRIN_PACKET_PACKETTYPE4_H

unsigned short const PACKET_TYPE4_BASE = 40000;
unsigned short const PACKET_TYPE4_MAX = 49999;

//맵서버 Task Message 용도
PACKET_DEF(PT_T_T_MAPSERVER_MESSAGE_START,	49000 )
//PACKET_DEF(PT_A_G_SEND_TOGROUND_PARTY,		49001 )
//PACKET_DEF(PT_A_G_MAPMOVE_TOGROUND_PARTY,	49002 )
PACKET_DEF(PT_A_T_UPDATE_PARTY_PROPERTY,	49003 )
PACKET_DEF(PT_A_G_SET_USERS_PARTYGUID,		49004 )
PACKET_DEF(PT_A_G_MAPMOVE,					49005 )
PACKET_DEF(PT_A_G_SEND_TOGROUND_USER,		49013 )
PACKET_DEF(PT_A_G_NFY_RELOAD_NPCQUEST,		49014 )

PACKET_DEF(PT_T_T_MAPSERVER_MESSAGE_END,	49999 )

#endif // WEAPON_LOHENGRIN_PACKET_PACKETTYPE4_H