#ifndef WEAPON_LOHENGRIN_CONFIG_SERVERTYPE_H
#define WEAPON_LOHENGRIN_CONFIG_SERVERTYPE_H

#include "CEL/Common.h"
#include "PacketStruct.h"

#pragma pack(1)

typedef enum {
	SERVER_BIT_NONE			= 0,
	SERVER_BIT_BASIC		= 0x00000001,
	SERVER_BIT_CENTER		= SERVER_BIT_BASIC << CEL::ST_CENTER,
	SERVER_BIT_MAP			= SERVER_BIT_BASIC << CEL::ST_MAP,
	SERVER_BIT_LOGIN		= SERVER_BIT_BASIC << CEL::ST_LOGIN,
	SERVER_BIT_SWITCH		= SERVER_BIT_BASIC << CEL::ST_SWITCH,
	SERVER_BIT_MCONTROL		= SERVER_BIT_BASIC << CEL::ST_MACHINE_CONTROL,
	SERVER_BIT_REALM		= SERVER_BIT_BASIC << CEL::ST_ITEM,
	SERVER_BIT_LOG			= SERVER_BIT_BASIC << CEL::ST_LOG,
	SERVER_BIT_GM			= SERVER_BIT_BASIC << CEL::ST_GMSERVER,
	SERVER_BIT_IMMGRATION	= SERVER_BIT_BASIC << CEL::ST_IMMIGRATION,
	SERVER_BIT_SUB_MCONTROL	= SERVER_BIT_BASIC << CEL::ST_SUB_MACHINE_CONTROL,

	SERVER_BIT_ALL_IN_SWITCH = SERVER_BIT_CENTER | SERVER_BIT_MAP | SERVER_BIT_SWITCH ,//| SERVER_BIT_CONTENTS
	SERVER_BIT_NOTMAP_PLAYERINFO = SERVER_BIT_CENTER | SERVER_BIT_SWITCH | SERVER_BIT_REALM ,//| SERVER_BIT_CONTENTS
	SERVER_BIT_ALL_PLAYERINFO = SERVER_BIT_CENTER | SERVER_BIT_MAP | SERVER_BIT_SWITCH | SERVER_BIT_REALM ,//| SERVER_BIT_CONTENTS 
	SERVER_BIT_ALL		= 0xFFFFFFFF,
} EServerBitType;

namespace LOCAL_MGR
{
typedef enum {
	ST_DR_NOT_SET			= 0x00000000,
	ST_DR_DEVELOP			= 0x00000001,	// 개발자 모드
	ST_DR_UNABLE_ANTIHACK	= 0x00000002,	// AntiHack 사용하지 않음
	ST_KOREA_NC_SERVICE		= 0x00000020,	// NCSoft 연동
} EDR_SERVICE_TYPE;

};

#pragma pack()

#endif // WEAPON_LOHENGRIN_CONFIG_SERVERTYPE_H